import { createHash,randomUUID } from 'node:crypto';
import { all,run } from '../storage/db.js';
import type { EvidenceGateResult } from '../editorial/evidence-gate.js';
import type { ClaimSourceMatrix } from '../editorial/claim-source-matrix.js';

export type EvidenceReviewStatus='pending'|'accepted'|'needs_fix';
export interface DraftEvidenceReview {
  draftId:string;ownerId:string;sourceIntelligenceId:string;evidenceGate:EvidenceGateResult;matrix:ClaimSourceMatrix;
  snapshotHash:string;status:EvidenceReviewStatus;reviewedAt?:string;reviewedBy?:string;reviewNote?:string;updatedAt:string;approvalAllowed:boolean;
}
type Row={draft_id:string;owner_id:string;source_intelligence_id:string;evidence_gate_json:string;matrix_json:string;snapshot_hash:string;status:EvidenceReviewStatus;reviewed_at?:string;reviewed_by?:string;review_note?:string;updated_at:string};
type EventRow={id:string;draft_id:string;owner_id:string;action:string;actor:string;status:EvidenceReviewStatus;snapshot_hash:string;note?:string;created_at:string};

for(const sql of[
`CREATE TABLE IF NOT EXISTS draft_evidence_reviews (draft_id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,source_intelligence_id TEXT NOT NULL,evidence_gate_json TEXT NOT NULL,matrix_json TEXT NOT NULL,snapshot_hash TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',reviewed_at TEXT,reviewed_by TEXT,review_note TEXT,updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS draft_evidence_events (id TEXT PRIMARY KEY,draft_id TEXT NOT NULL,owner_id TEXT NOT NULL,action TEXT NOT NULL,actor TEXT NOT NULL,status TEXT NOT NULL,snapshot_hash TEXT NOT NULL,note TEXT,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS prepared_evidence_bundles (id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,source_intelligence_id TEXT NOT NULL,evidence_gate_json TEXT NOT NULL,matrix_json TEXT NOT NULL,bundle_hash TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,consumed_at TEXT,consumed_draft_id TEXT)`,
'CREATE INDEX IF NOT EXISTS idx_prepared_evidence_owner ON prepared_evidence_bundles(owner_id,expires_at DESC)',
'CREATE INDEX IF NOT EXISTS idx_draft_evidence_owner ON draft_evidence_reviews(owner_id,updated_at DESC)',
'CREATE INDEX IF NOT EXISTS idx_draft_evidence_events ON draft_evidence_events(owner_id,draft_id,created_at DESC)'
]){try{run(sql)}catch{}}
const stable=(v:unknown):string=>v===null||typeof v!=='object'?JSON.stringify(v)??'null':Array.isArray(v)?`[${v.map(stable).join(',')}]`:`{${Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${stable(x)}`).join(',')}}`;
const hash=(gate:EvidenceGateResult,matrix:ClaimSourceMatrix)=>createHash('sha256').update(stable({gate,matrix:{...matrix,createdAt:undefined}})).digest('hex');
function map(r:Row):DraftEvidenceReview{const evidenceGate=JSON.parse(r.evidence_gate_json) as EvidenceGateResult,matrix=JSON.parse(r.matrix_json) as ClaimSourceMatrix;return{draftId:r.draft_id,ownerId:r.owner_id,sourceIntelligenceId:r.source_intelligence_id,evidenceGate,matrix,snapshotHash:r.snapshot_hash,status:r.status,reviewedAt:r.reviewed_at||undefined,reviewedBy:r.reviewed_by||undefined,reviewNote:r.review_note||undefined,updatedAt:r.updated_at,approvalAllowed:r.status==='accepted'&&evidenceGate.status!=='block'}}
function event(draftId:string,ownerId:string,action:string,actor:string,status:EvidenceReviewStatus,snapshotHash:string,note?:string){run('INSERT INTO draft_evidence_events(id,draft_id,owner_id,action,actor,status,snapshot_hash,note,created_at) VALUES(?,?,?,?,?,?,?,?,?)',randomUUID(),draftId,ownerId,action,actor,status,snapshotHash,note||null,new Date().toISOString())}
export function saveDraftEvidence(draftId:string,ownerId:string,input:{sourceIntelligenceId:string;evidenceGate:EvidenceGateResult;matrix:ClaimSourceMatrix},actor='system:auto-producer'){
  const draft=all<{id:string}>('SELECT id FROM drafts WHERE id=? AND owner_id=? LIMIT 1',draftId,ownerId)[0];if(!draft)throw new Error('Draft not found for evidence snapshot');const intel=all<{id:string}>('SELECT id FROM source_intelligence WHERE id=? AND owner_id=? LIMIT 1',input.sourceIntelligenceId,ownerId)[0];if(!intel)throw new Error('Source Intelligence không thuộc owner hoặc không tồn tại');if(input.matrix.sourceIntelligenceId!==input.sourceIntelligenceId)throw new Error('Claim → Source Matrix không khớp Source Intelligence');
  const snapshotHash=hash(input.evidenceGate,input.matrix),existing=all<Row>('SELECT * FROM draft_evidence_reviews WHERE draft_id=? AND owner_id=? LIMIT 1',draftId,ownerId)[0];if(existing?.snapshot_hash===snapshotHash)return map(existing);
  const now=new Date().toISOString();run(`INSERT INTO draft_evidence_reviews(draft_id,owner_id,source_intelligence_id,evidence_gate_json,matrix_json,snapshot_hash,status,reviewed_at,reviewed_by,review_note,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(draft_id) DO UPDATE SET owner_id=excluded.owner_id,source_intelligence_id=excluded.source_intelligence_id,evidence_gate_json=excluded.evidence_gate_json,matrix_json=excluded.matrix_json,snapshot_hash=excluded.snapshot_hash,status='pending',reviewed_at=NULL,reviewed_by=NULL,review_note=NULL,updated_at=excluded.updated_at`,draftId,ownerId,input.sourceIntelligenceId,JSON.stringify(input.evidenceGate),JSON.stringify(input.matrix),snapshotHash,'pending',null,null,null,now);event(draftId,ownerId,existing?'evidence_replaced':'evidence_created',actor,'pending',snapshotHash);return getDraftEvidence(draftId,ownerId)!;
}

export function createPreparedEvidenceBundle(ownerId:string,input:{sourceIntelligenceId:string;evidenceGate:EvidenceGateResult;matrix:ClaimSourceMatrix},ttlMinutes=30){
  const intel=all<{id:string}>('SELECT id FROM source_intelligence WHERE id=? AND owner_id=? LIMIT 1',input.sourceIntelligenceId,ownerId)[0];if(!intel)throw new Error('Source Intelligence không tồn tại cho evidence bundle');if(input.matrix.sourceIntelligenceId!==input.sourceIntelligenceId)throw new Error('Evidence bundle matrix mismatch');
  const id=randomUUID(),createdAt=new Date().toISOString(),expiresAt=new Date(Date.now()+Math.max(5,Math.min(120,ttlMinutes))*60000).toISOString(),bundleHash=hash(input.evidenceGate,input.matrix);run('DELETE FROM prepared_evidence_bundles WHERE expires_at<? OR consumed_at IS NOT NULL',new Date(Date.now()-86400000).toISOString());run('INSERT INTO prepared_evidence_bundles(id,owner_id,source_intelligence_id,evidence_gate_json,matrix_json,bundle_hash,created_at,expires_at) VALUES(?,?,?,?,?,?,?,?)',id,ownerId,input.sourceIntelligenceId,JSON.stringify(input.evidenceGate),JSON.stringify(input.matrix),bundleHash,createdAt,expiresAt);return{id,sourceIntelligenceId:input.sourceIntelligenceId,bundleHash,createdAt,expiresAt};
}
export function consumePreparedEvidenceBundle(bundleId:string,draftId:string,ownerId:string,actor='system:auto-producer'){
  const row=all<{id:string;source_intelligence_id:string;evidence_gate_json:string;matrix_json:string;expires_at:string;consumed_at?:string}>('SELECT * FROM prepared_evidence_bundles WHERE id=? AND owner_id=? LIMIT 1',bundleId,ownerId)[0];if(!row)throw new Error('Evidence bundle không tồn tại hoặc không thuộc owner');if(row.consumed_at)throw new Error('Evidence bundle đã được sử dụng');if(Date.parse(row.expires_at)<=Date.now())throw new Error('Evidence bundle đã hết hạn; cần chạy lại Auto Producer');const evidence=saveDraftEvidence(draftId,ownerId,{sourceIntelligenceId:row.source_intelligence_id,evidenceGate:JSON.parse(row.evidence_gate_json),matrix:JSON.parse(row.matrix_json)},actor);run('UPDATE prepared_evidence_bundles SET consumed_at=?,consumed_draft_id=? WHERE id=? AND owner_id=? AND consumed_at IS NULL',new Date().toISOString(),draftId,bundleId,ownerId);return evidence;
}
export function getDraftEvidence(draftId:string,ownerId:string){const r=all<Row>('SELECT * FROM draft_evidence_reviews WHERE draft_id=? AND owner_id=? LIMIT 1',draftId,ownerId)[0];return r?map(r):undefined}
export function setDraftEvidenceReview(draftId:string,ownerId:string,status:Exclude<EvidenceReviewStatus,'pending'>,actor:string,note=''){
  const current=getDraftEvidence(draftId,ownerId);if(!current)throw new Error('Evidence snapshot not found');const now=new Date().toISOString(),cleanNote=String(note||'').trim().slice(0,1000);if(status==='accepted'&&current.evidenceGate.status==='block')throw new Error('Evidence BLOCK không thể được xác nhận để duyệt');if(status==='accepted'&&(current.matrix.unmappedCorroboratedClaimCount>0||current.matrix.uncertainClaimCount>0)&&cleanNote.length<10)throw new Error('Evidence còn claim cần review; phải ghi chú xác minh trước khi xác nhận');run('UPDATE draft_evidence_reviews SET status=?,reviewed_at=?,reviewed_by=?,review_note=?,updated_at=? WHERE draft_id=? AND owner_id=?',status,now,actor,cleanNote||null,now,draftId,ownerId);event(draftId,ownerId,status==='accepted'?'evidence_accepted':'evidence_needs_fix',actor,status,current.snapshotHash,cleanNote);return getDraftEvidence(draftId,ownerId)!;
}
export function evidenceApprovalAllowed(draftId:string,ownerId:string){const x=getDraftEvidence(draftId,ownerId);return !x||x.approvalAllowed}
export function listDraftEvidenceEvents(draftId:string,ownerId:string,limit=20){return all<EventRow>('SELECT * FROM draft_evidence_events WHERE draft_id=? AND owner_id=? ORDER BY created_at DESC LIMIT ?',draftId,ownerId,Math.max(1,Math.min(100,limit))).map(r=>({id:r.id,draftId:r.draft_id,ownerId:r.owner_id,action:r.action,actor:r.actor,status:r.status,snapshotHash:r.snapshot_hash,note:r.note||undefined,createdAt:r.created_at}))}
