import * as cheerio from 'cheerio';
import { lookup } from 'node:dns/promises';
import { isIP } from 'node:net';
import { all, run } from '../storage/db.js';

export interface RssSource { id:string; ownerId:string; name:string; url:string; createdAt:string; lastScanAt?:string; lastError?:string; locked:boolean; managed:boolean; }
export interface RssItem { id:string; ownerId:string; sourceId:string; sourceName:string; title:string; link:string; summary?:string; imageUrl?:string; publishedAt?:string; discoveredAt:string; }

type SourceRow={id:string;owner_id?:string;name:string;url:string;created_at:string;last_scan_at?:string;last_error?:string;locked?:number;managed?:number};
type ItemRow={id:string;owner_id?:string;source_id:string;source_name:string;title:string;link:string;summary?:string;image_url?:string;published_at?:string;discovered_at:string};
const mapSource=(r:SourceRow):RssSource=>({id:r.id,ownerId:r.owner_id||'legacy-admin',name:r.name,url:r.url,createdAt:r.created_at,lastScanAt:r.last_scan_at||undefined,lastError:r.last_error||undefined,locked:Boolean(r.locked),managed:Boolean(r.managed)});
const mapItem=(r:ItemRow):RssItem=>({id:r.id,ownerId:r.owner_id||'legacy-admin',sourceId:r.source_id,sourceName:r.source_name,title:r.title,link:r.link,summary:r.summary||undefined,imageUrl:r.image_url||undefined,publishedAt:r.published_at||undefined,discoveredAt:r.discovered_at});
export const rssSources:RssSource[]=all<SourceRow>('SELECT * FROM rss_sources_tenant ORDER BY created_at DESC').map(mapSource);
export const rssItems:RssItem[]=all<ItemRow>('SELECT * FROM rss_items_tenant ORDER BY discovered_at DESC LIMIT 300').map(mapItem);
const seen=new Set(rssItems.map(i=>i.ownerId+'|'+i.link));

function privateIp(ip:string){if(ip.includes(':'))return ip==='::1'||ip.startsWith('fc')||ip.startsWith('fd')||ip.startsWith('fe80:');const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168);}
async function assertPublicUrl(raw:string){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw new Error('RSS chỉ hỗ trợ HTTP/HTTPS');if(isIP(u.hostname)){if(privateIp(u.hostname))throw new Error('RSS private/internal host bị chặn');}else{const rows=await lookup(u.hostname,{all:true});if(!rows.length||rows.some(x=>privateIp(x.address)))throw new Error('RSS private/internal host bị chặn');}return u;}
function text($:cheerio.CheerioAPI,node:any,selector:string){return $(node).find(selector).first().text().replace(/\s+/g,' ').trim();}
function attr($:cheerio.CheerioAPI,node:any,selector:string,name:string){return $(node).find(selector).first().attr(name)?.trim()||'';}
function directRssUrl(raw:string){const url=new URL(raw);if(url.hostname==='news.google.com'&&url.pathname.startsWith('/rss'))throw new Error('Không dùng RSS trung gian Google News. Hãy dùng RSS trực tiếp của cơ quan phát hành.');return url.toString();}

export function addRssSource(input:{ownerId?:string;name?:string;url:string;locked?:boolean;managed?:boolean}){const ownerId=input.ownerId||'legacy-admin',url=directRssUrl(input.url),existing=rssSources.find(s=>s.ownerId===ownerId&&s.url===url);if(existing)return existing;const host=new URL(url).hostname.replace(/^www\./,'');const source:RssSource={id:crypto.randomUUID(),ownerId,name:(input.name||host).slice(0,120),url,createdAt:new Date().toISOString(),locked:Boolean(input.locked),managed:Boolean(input.managed)};rssSources.unshift(source);run('INSERT INTO rss_sources_tenant(id,owner_id,name,url,created_at,locked,managed) VALUES(?,?,?,?,?,?,?)',source.id,source.ownerId,source.name,source.url,source.createdAt,source.locked?1:0,source.managed?1:0);return source;}

export function updateRssSource(id:string,input:{name?:string;url?:string}){const source=rssSources.find(s=>s.id===id);if(!source)return undefined;const nextUrl=directRssUrl(input.url?.trim()||source.url);const duplicate=rssSources.find(s=>s.id!==id&&s.ownerId===source.ownerId&&s.url===nextUrl);if(duplicate)throw new Error('RSS URL đã tồn tại');const nextName=(input.name?.trim()||new URL(nextUrl).hostname.replace(/^www\./,'')).slice(0,120);source.name=nextName;source.url=nextUrl;source.lastError=undefined;run('UPDATE rss_sources_tenant SET name=?,url=?,last_error=NULL WHERE id=?',source.name,source.url,source.id);for(const item of rssItems.filter(x=>x.sourceId===id)){item.sourceName=source.name;run('UPDATE rss_items_tenant SET source_name=? WHERE id=?',source.name,item.id)}return source;}

export function setRssSourceLock(id:string,locked:boolean){const source=rssSources.find(s=>s.id===id);if(!source)return undefined;source.locked=locked;if(locked)source.managed=false;run('UPDATE rss_sources_tenant SET locked=?,managed=? WHERE id=?',source.locked?1:0,source.managed?1:0,id);return source}

export function deleteRssSource(id:string,deleteItems=true){const index=rssSources.findIndex(s=>s.id===id);if(index<0)return false;if(deleteItems){const removed=rssItems.filter(x=>x.sourceId===id);for(const item of removed)seen.delete(item.ownerId+'|'+item.link);for(let i=rssItems.length-1;i>=0;i--)if(rssItems[i].sourceId===id)rssItems.splice(i,1);run('DELETE FROM rss_items_tenant WHERE source_id=?',id)}rssSources.splice(index,1);run('DELETE FROM rss_sources_tenant WHERE id=?',id);return true;}

export function deleteRssItem(id:string){const index=rssItems.findIndex(x=>x.id===id);if(index<0)return false;seen.delete(rssItems[index].ownerId+'|'+rssItems[index].link);rssItems.splice(index,1);run('DELETE FROM rss_items_tenant WHERE id=?',id);return true;}

export function deleteRssItems(input:{ownerId?:string;sourceId?:string;ids?:string[];all?:boolean}){let targets:RssItem[]=[];const available=input.ownerId?rssItems.filter(x=>x.ownerId===input.ownerId):rssItems;if(input.all)targets=[...available];else if(input.ids?.length){const set=new Set(input.ids);targets=available.filter(x=>set.has(x.id))}else if(input.sourceId)targets=available.filter(x=>x.sourceId===input.sourceId);if(!targets.length)return 0;const ids=new Set(targets.map(x=>x.id));for(const item of targets)seen.delete(item.ownerId+'|'+item.link);for(let i=rssItems.length-1;i>=0;i--)if(ids.has(rssItems[i].id))rssItems.splice(i,1);if(input.all&&!input.ownerId)run('DELETE FROM rss_items_tenant');else if(input.sourceId&&!input.ids?.length)run('DELETE FROM rss_items_tenant WHERE source_id=?',input.sourceId);else for(const id of ids)run('DELETE FROM rss_items_tenant WHERE id=?',id);return targets.length;}

export async function scanRssSource(source:RssSource){await assertPublicUrl(source.url);try{const r=await fetch(source.url,{headers:{'user-agent':'Mozilla/5.0 (compatible; BienNoiNhoAutoMedia/1.3)'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`RSS HTTP ${r.status}`);const xml=await r.text();if(xml.length>5_000_000)throw new Error('RSS quá lớn');const $=cheerio.load(xml,{xmlMode:true});const nodes=$('item').length?$('item').toArray():$('entry').toArray();let added=0;for(const n of nodes.slice(0,50)){const title=text($,n,'title');let link=text($,n,'link')||attr($,n,'link','href');const guid=text($,n,'guid')||text($,n,'id');const rawSummary=text($,n,'content\\:encoded')||text($,n,'description')||text($,n,'summary');const summary=rawSummary.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,6000)||undefined;const rawImage=attr($,n,'media\\:content','url')||attr($,n,'media\\:thumbnail','url')||attr($,n,'enclosure','url');let imageUrl:string|undefined;try{if(rawImage)imageUrl=new URL(rawImage,source.url).toString()}catch{}const publishedAt=text($,n,'pubDate')||text($,n,'published')||text($,n,'updated')||undefined;if(!title||!link)continue;try{link=new URL(link,source.url).toString();}catch{continue;}const key=source.ownerId+'|'+(guid||link);if(seen.has(key)||rssItems.some(i=>i.ownerId===source.ownerId&&i.link===link))continue;seen.add(key);const item:RssItem={id:crypto.randomUUID(),ownerId:source.ownerId,sourceId:source.id,sourceName:source.name,title:title.slice(0,180),link,summary,imageUrl,publishedAt,discoveredAt:new Date().toISOString()};rssItems.unshift(item);run('INSERT OR IGNORE INTO rss_items_tenant(id,owner_id,source_id,source_name,title,link,summary,image_url,published_at,discovered_at) VALUES(?,?,?,?,?,?,?,?,?,?)',item.id,item.ownerId,item.sourceId,item.sourceName,item.title,item.link,item.summary||null,item.imageUrl||null,item.publishedAt||null,item.discoveredAt);added++;}rssItems.splice(300);source.lastScanAt=new Date().toISOString();source.lastError=undefined;run('UPDATE rss_sources_tenant SET last_scan_at=?,last_error=NULL WHERE id=?',source.lastScanAt,source.id);return {added,total:nodes.length};}catch(e){source.lastScanAt=new Date().toISOString();source.lastError=e instanceof Error?e.message:String(e);run('UPDATE rss_sources_tenant SET last_scan_at=?,last_error=? WHERE id=?',source.lastScanAt,source.lastError,source.id);throw e;}}
export async function scanAllRss(ownerId?:string){let added=0;const sources=ownerId?rssSources.filter(x=>x.ownerId===ownerId):rssSources;for(const s of sources){try{added+=(await scanRssSource(s)).added}catch{}}return {added,sources:sources.length,items:ownerId?rssItems.filter(x=>x.ownerId===ownerId).length:rssItems.length};}
