import { randomUUID } from 'node:crypto';
import '../queue/production.js';
import { all,run } from '../storage/db.js';
import { getReview } from '../review/store.js';
import { artifactIntegritySnapshot } from '../video/provenance.js';

export type ConsistencySeverity='blocker'|'warn'|'info';
export interface ConsistencyIssue{code:string;severity:ConsistencySeverity;entityType:string;entityId:string;message:string;repairable:boolean}
export interface ConsistencySnapshot{ownerId:string;ok:boolean;blockers:number;warnings:number;issues:ConsistencyIssue[];checkedAt:string}

type QueueRow={draft_id:string;owner_id:string;title:string;status:string;job_id?:string};
type DraftRow={id:string;owner_id:string;title:string;status:string};
type RenderRow={id:string;draft_id:string;owner_id:string;status:string;output?:string;created_at:string};
type PublishRow={id:string;owner_id:string;render_job_id:string;draft_id:string;platform:string;status:string;dry_run:number;remote_id?:string;remote_url?:string;created_at:string};
type SessionRow={publish_job_id:string;owner_id:string;state:string;remote_id?:string;remote_url?:string};

for(const sql of[
`CREATE TABLE IF NOT EXISTS system_consistency_runs (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, started_at TEXT NOT NULL, completed_at TEXT NOT NULL,
 blockers INTEGER NOT NULL, warnings INTEGER NOT NULL, repairs INTEGER NOT NULL, summary_json TEXT NOT NULL
)`,
`CREATE TABLE IF NOT EXISTS system_consistency_issues (
 id TEXT PRIMARY KEY, run_id TEXT NOT NULL, owner_id TEXT NOT NULL, code TEXT NOT NULL, severity TEXT NOT NULL,
 entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, message TEXT NOT NULL, repairable INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL
)`,
'CREATE INDEX IF NOT EXISTS idx_consistency_runs_owner ON system_consistency_runs(owner_id,completed_at DESC)',
'CREATE INDEX IF NOT EXISTS idx_consistency_issues_run ON system_consistency_issues(run_id,severity)'
]){try{run(sql)}catch{}}

function issue(code:string,severity:ConsistencySeverity,entityType:string,entityId:string,message:string,repairable=false):ConsistencyIssue{return{code,severity,entityType,entityId,message,repairable}}
function latestRender(draftId:string,ownerId:string){return all<RenderRow>('SELECT id,draft_id,owner_id,status,output,created_at FROM render_jobs WHERE draft_id=? AND owner_id=? ORDER BY created_at DESC LIMIT 1',draftId,ownerId)[0]}
function expectedQueueStatus(draft:DraftRow){const r=latestRender(draft.id,draft.owner_id);if(r){if(r.status==='queued'||r.status==='rendering')return{status:'rendering',jobId:r.id};if(r.status==='ready')return{status:'completed',jobId:r.id};if(r.status==='failed')return{status:'failed',jobId:r.id}}return{status:getReview(draft.id,draft.owner_id).approvalCurrent?'approved':'waiting_review',jobId:undefined}}

function collect(ownerId:string):ConsistencyIssue[]{
 const issues:ConsistencyIssue[]=[],drafts=all<DraftRow>('SELECT id,owner_id,title,status FROM drafts WHERE owner_id=?',ownerId),allQueues=all<QueueRow>('SELECT draft_id,owner_id,title,status,job_id FROM production_queue'),draftMap=new Map(drafts.map(x=>[x.id,x])),queueMap=new Map(allQueues.map(x=>[x.draft_id,x]));
 for(const d of drafts){const q=queueMap.get(d.id),expected=expectedQueueStatus(d);if(!q)issues.push(issue('queue_missing','warn','draft',d.id,'Draft chưa có Production Queue row; có thể phục hồi an toàn.',true));else{if(q.owner_id!==d.owner_id||q.title!==d.title)issues.push(issue('queue_metadata_mismatch','warn','production_queue',d.id,'Production Queue owner/title lệch với Draft.',true));if(q.status!==expected.status||String(q.job_id||'')!==String(expected.jobId||''))issues.push(issue('queue_status_mismatch','warn','production_queue',d.id,`Queue=${q.status}/${q.job_id||'-'} nhưng expected=${expected.status}/${expected.jobId||'-'}.`,true))}}
 for(const q of allQueues.filter(x=>x.owner_id===ownerId))if(!draftMap.has(q.draft_id))issues.push(issue('queue_orphan','warn','production_queue',q.draft_id,'Production Queue không còn Draft nguồn; không tự xóa để giữ audit evidence.'));
 const renderRows=all<RenderRow>('SELECT id,draft_id,owner_id,status,output,created_at FROM render_jobs WHERE owner_id=?',ownerId);for(const r of renderRows){if(!draftMap.has(r.draft_id))issues.push(issue('render_orphan',r.status==='queued'||r.status==='rendering'||r.status==='ready'?'blocker':'warn','render_job',r.id,`Render ${r.status} không còn Draft nguồn.`));if(r.status==='ready'&&!r.output)issues.push(issue('ready_render_no_output','blocker','render_job',r.id,'Render READY nhưng không có output path.'))}
 const publish=all<PublishRow>('SELECT id,owner_id,render_job_id,draft_id,platform,status,dry_run,remote_id,remote_url,created_at FROM publish_jobs WHERE owner_id=?',ownerId),renderIds=new Set(renderRows.map(x=>x.id));for(const p of publish){const active=['pending','scheduled','publishing','needs_reconcile'].includes(p.status);if(active&&!draftMap.has(p.draft_id))issues.push(issue('active_publish_missing_draft','blocker','publish_job',p.id,'Publish job đang hoạt động nhưng Draft không tồn tại.'));if(active&&!renderIds.has(p.render_job_id))issues.push(issue('active_publish_missing_render','blocker','publish_job',p.id,'Publish job đang hoạt động nhưng Render job không tồn tại.'));if(active&&!p.dry_run&&draftMap.has(p.draft_id)&&!getReview(p.draft_id,ownerId).approvalCurrent)issues.push(issue('active_publish_stale_review','blocker','publish_job',p.id,'LIVE publish đang hoạt động với Review approval stale.'));if(p.status==='published'&&!p.dry_run&&!p.remote_id)issues.push(issue('published_missing_remote_id','blocker','publish_job',p.id,'Job đã marked published nhưng thiếu remote ID.'));if(p.status==='published'&&!p.dry_run&&p.platform==='youtube'){const link=all<{n:number}>('SELECT COUNT(*) n FROM artifact_publish_links WHERE publish_job_id=? AND owner_id=?',p.id,ownerId)[0]?.n||0;if(!link)issues.push(issue('published_missing_provenance_link','warn','publish_job',p.id,'YouTube job published nhưng thiếu artifact→remote provenance link.'))}}
 const sessions=all<SessionRow>('SELECT publish_job_id,owner_id,state,remote_id,remote_url FROM youtube_upload_sessions WHERE owner_id=?',ownerId),publishMap=new Map(publish.map(x=>[x.id,x]));for(const s of sessions){const p=publishMap.get(s.publish_job_id);if(!p&&s.state==='active')issues.push(issue('active_session_orphan','blocker','upload_session',s.publish_job_id,'YouTube upload session ACTIVE nhưng publish job không tồn tại.'));if(p&&s.state==='active'&&['published','failed','cancelled'].includes(p.status))issues.push(issue('active_session_terminal_job','warn','upload_session',s.publish_job_id,`Upload session ACTIVE nhưng publish job đã ${p.status}; có thể repair local state an toàn.`,true));if(p?.status==='published'&&s.state==='completed'&&p.remote_id&&s.remote_id&&p.remote_id!==s.remote_id)issues.push(issue('remote_id_mismatch','blocker','upload_session',s.publish_job_id,'Remote ID của upload session khác publish job.'))}
 const artifact=artifactIntegritySnapshot(ownerId);if(artifact.activeLiveInvalid)issues.push(issue('active_live_artifact_invalid','blocker','artifact','live',`${artifact.activeLiveInvalid} LIVE target thiếu/quarantine Render Manifest.`));
 return issues;
}

function repair(ownerId:string,issues:ConsistencyIssue[]){let repaired=0;const now=()=>new Date().toISOString();for(const i of issues){if(!i.repairable)continue;try{if(i.code==='queue_missing'||i.code==='queue_metadata_mismatch'||i.code==='queue_status_mismatch'){const d=all<DraftRow>('SELECT id,owner_id,title,status FROM drafts WHERE id=? AND owner_id=? LIMIT 1',i.entityId,ownerId)[0];if(d){const expected=expectedQueueStatus(d),ts=now();run(`INSERT INTO production_queue(draft_id,owner_id,title,status,job_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(draft_id) DO UPDATE SET owner_id=excluded.owner_id,title=excluded.title,status=excluded.status,job_id=excluded.job_id,updated_at=excluded.updated_at`,d.id,d.owner_id,d.title,expected.status,expected.jobId||null,ts,ts);repaired++}}else if(i.code==='active_session_terminal_job'){const p=all<PublishRow>('SELECT id,owner_id,render_job_id,draft_id,platform,status,dry_run,remote_id,remote_url,created_at FROM publish_jobs WHERE id=? AND owner_id=? LIMIT 1',i.entityId,ownerId)[0];if(p?.status==='published'&&p.remote_id){run("UPDATE youtube_upload_sessions SET state='completed',next_offset=file_size,remote_id=?,remote_url=?,updated_at=? WHERE publish_job_id=? AND owner_id=?",p.remote_id,p.remote_url||null,now(),p.id,ownerId);repaired++}else if(p&&['failed','cancelled'].includes(p.status)){run("UPDATE youtube_upload_sessions SET state='failed',updated_at=? WHERE publish_job_id=? AND owner_id=?",now(),p.id,ownerId);repaired++}}}catch(e){console.warn(`[consistency] safe repair failed ${i.code}/${i.entityId}: ${e instanceof Error?e.message:String(e)}`)}}return repaired}

export function consistencySnapshot(ownerId:string):ConsistencySnapshot{const issues=collect(ownerId),blockers=issues.filter(x=>x.severity==='blocker').length,warnings=issues.filter(x=>x.severity==='warn').length;return{ownerId,ok:blockers===0,blockers,warnings,issues,checkedAt:new Date().toISOString()}}
export function runConsistencyAudit(ownerId:string,options:{repairSafe?:boolean;persistent?:boolean}={}){const startedAt=new Date().toISOString(),before=collect(ownerId),repairs=options.repairSafe===false?0:repair(ownerId,before),snapshot=consistencySnapshot(ownerId),completedAt=new Date().toISOString();if(options.persistent!==false){const id=randomUUID(),summary={before:{blockers:before.filter(x=>x.severity==='blocker').length,warnings:before.filter(x=>x.severity==='warn').length},after:{blockers:snapshot.blockers,warnings:snapshot.warnings},repairs};run('INSERT INTO system_consistency_runs(id,owner_id,started_at,completed_at,blockers,warnings,repairs,summary_json) VALUES(?,?,?,?,?,?,?,?)',id,ownerId,startedAt,completedAt,snapshot.blockers,snapshot.warnings,repairs,JSON.stringify(summary));for(const x of snapshot.issues)run('INSERT INTO system_consistency_issues(id,run_id,owner_id,code,severity,entity_type,entity_id,message,repairable,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',randomUUID(),id,ownerId,x.code,x.severity,x.entityType,x.entityId,x.message,x.repairable?1:0,completedAt);return{runId:id,repairs,...snapshot}}return{repairs,...snapshot}}
export function latestConsistencyRuns(ownerId:string,limit=10){return all<any>('SELECT id,owner_id,started_at,completed_at,blockers,warnings,repairs,summary_json FROM system_consistency_runs WHERE owner_id=? ORDER BY completed_at DESC LIMIT ?',ownerId,Math.max(1,Math.min(50,limit))).map(x=>({id:x.id,startedAt:x.started_at,completedAt:x.completed_at,blockers:Number(x.blockers),warnings:Number(x.warnings),repairs:Number(x.repairs)}))}
export function runAllConsistencyAudits(){const owners=all<{id:string}>("SELECT id FROM accounts WHERE status='active'").map(x=>x.id);for(const owner of owners)try{runConsistencyAudit(owner,{repairSafe:true,persistent:true})}catch(e){console.warn(`[consistency] audit failed for ${owner}: ${e instanceof Error?e.message:String(e)}`)}}
const auditIntervalMs=Math.max(60_000,Number(process.env.CONSISTENCY_AUDIT_INTERVAL_MS||300000));if(process.env.CONSISTENCY_AUDITOR_ENABLED!=='false'){const boot=setTimeout(()=>runAllConsistencyAudits(),20_000);boot.unref();const timer=setInterval(()=>runAllConsistencyAudits(),auditIntervalMs);timer.unref()}
