import { productionAnalyticsSnapshot } from '../analytics/production.js';
import { listPublishJobs } from '../publish/queue.js';
import { publisherDeploymentReadiness } from '../publish/deployment-readiness.js';
import { renderJobs } from '../video/job.js';
import { listAuditEvents } from './audit.js';
import { monitorIncidents, productionMonitorSnapshot } from './monitor.js';

export type OpsSeverity='green'|'yellow'|'red';
export type OpsIntent='overview'|'render-slow'|'stuck-jobs'|'publish'|'youtube-live'|'resources'|'incidents'|'activity';
export interface OpsAssistantAnswer{mode:'rules'|'llm';intent:OpsIntent;severity:OpsSeverity;summary:string;findings:string[];recommendations:string[];evidence:Array<{label:string;value:string}>;generatedAt:string;readOnly:true;provider?:string}
type LlmProvider={id:'gemini'|'custom';url:string;key:string;model?:string};

function n(v:unknown,fallback=0){const x=Number(v);return Number.isFinite(x)?x:fallback}
function pct(v:unknown){return v==null?'—':`${n(v).toFixed(1).replace('.0','')}%`}
function duration(v:unknown){const x=n(v,-1);if(x<0)return'—';if(x<1000)return`${Math.round(x)} ms`;if(x<60000)return`${Math.round(x/1000)} giây`;if(x<3600000)return`${Math.round(x/60000)} phút`;return`${Math.round(x/360000)/10} giờ`}
function classify(q:string):OpsIntent{const s=q.toLocaleLowerCase('vi-VN');if(/youtube|live|oauth|kênh/.test(s))return'youtube-live';if(/kẹt|treo|stuck|backlog|hàng đợi|queue/.test(s))return'stuck-jobs';if(/render.*(chậm|lâu)|chậm.*render|tốc độ render/.test(s))return'render-slow';if(/publish|đăng|xuất bản/.test(s))return'publish';if(/ram|cpu|disk|ổ đĩa|4\s*gb|wyse|tối ưu|tài nguyên/.test(s))return'resources';if(/incident|sự cố|cảnh báo|red|yellow/.test(s))return'incidents';if(/ai làm|ai đã|hoạt động|audit|timeline|gần đây/.test(s))return'activity';return'overview'}
function worst(...v:OpsSeverity[]):OpsSeverity{return v.includes('red')?'red':v.includes('yellow')?'yellow':'green'}
function uniq(v:string[]){return[...new Set(v.filter(Boolean))].slice(0,8)}
function question(v:unknown){const q=String(v||'').replace(/\s+/g,' ').trim();if(q.length<3||q.length>600)throw new Error('Câu hỏi cần từ 3 đến 600 ký tự');return q}

export async function opsAssistantContext(ownerId:string){const monitor=await productionMonitorSnapshot(ownerId);return{monitor,analytics7:productionAnalyticsSnapshot(ownerId,7),analytics30:productionAnalyticsSnapshot(ownerId,30),incidents:monitorIncidents(ownerId,30),audit:listAuditEvents(ownerId,20),renders:renderJobs.filter(x=>x.ownerId===ownerId).slice(0,30),publishes:listPublishJobs(ownerId).slice(0,50),deployment:publisherDeploymentReadiness(ownerId)}}

function rulesAnswer(q:string,ctx:Awaited<ReturnType<typeof opsAssistantContext>>):OpsAssistantAnswer{
  const intent=classify(q),m=ctx.monitor.components,a=ctx.analytics7,findings:string[]=[],recommendations:string[]=[],evidence:Array<{label:string;value:string}>=[];
  const active=ctx.incidents.filter(x=>x.active),renderQueue=n(m.render.pending),publishQueue=n(ctx.monitor.publishQueue?.queued),renderLatency=n(a.kpis.avgRenderQueueMs,-1),renderProcessing=n(a.kpis.avgRenderProcessingMs,-1),publishLatency=n(a.kpis.avgPublishQueueMs,-1),stuckPublish=ctx.publishes.filter(x=>x.status==='publishing'&&Date.now()-Date.parse(x.updatedAt)>n(m.publish.stuckMs,900000));
  let severity:OpsSeverity=ctx.monitor.overall;
  const resources=()=>{findings.push(`RAM khả dụng ${n(m.memory.availableMb)} MB${m.memory.cgroupMemoryUsagePct!=null?`, container dùng ${n(m.memory.cgroupMemoryUsagePct)}%`:''}.`);findings.push(`CPU load/core ${n(m.cpu.loadPerCpu).toFixed(2)}; disk còn ${n((m.disk as any).freeMb)} MB.`);evidence.push({label:'RAM',value:`${n(m.memory.availableMb)} MB`},{label:'CPU load/core',value:n(m.cpu.loadPerCpu).toFixed(2)},{label:'Disk free',value:`${n((m.disk as any).freeMb)} MB`})};
  if(intent==='render-slow'){
    severity=worst(m.memory.severity,m.cpu.severity,m.disk.severity,m.render.severity);findings.push(`Render queue ${renderQueue} job; queue latency TB 7 ngày ${duration(renderLatency)}; processing TB ${duration(renderProcessing)}.`);if(m.render.watchdog?.stalled)findings.push(`Render worker STALLED tại ${m.render.watchdog.stage}.`);if(ctx.monitor.render.paused)findings.push('Render Queue đang PAUSED.');resources();if(m.memory.severity!=='green')recommendations.push('Giảm áp lực RAM; giữ single worker và tránh chạy VieNeu/local AI đồng thời với FFmpeg.');if(m.disk.severity!=='green')recommendations.push('Dọn output hoặc tăng dung lượng trống trước khi render tiếp.');if(m.cpu.severity!=='green')recommendations.push('Giảm motion/độ phân giải hoặc tránh tác vụ CPU nặng song song.');if(renderQueue>=n(m.render.warnBacklog,5))recommendations.push('Xử lý job failed/stale trước khi nạp thêm batch lớn.');if(!recommendations.length)recommendations.push('Tài nguyên ổn; so sánh media download, TTS và FFmpeg để tìm bottleneck nội dung.');
  }else if(intent==='stuck-jobs'){
    const rs=Boolean(m.render.watchdog?.stalled),rf=ctx.renders.filter(x=>x.status==='failed'),pf=ctx.publishes.filter(x=>x.status==='failed');severity=rs||stuckPublish.length?'red':rf.length||pf.length||renderQueue||publishQueue?'yellow':'green';findings.push(`Render: ${renderQueue} chờ, ${rf.length} failed${rs?`, STALLED tại ${m.render.watchdog?.stage}`:''}.`);findings.push(`Publish: ${publishQueue} chờ, ${pf.length} failed, ${stuckPublish.length} publishing quá ngưỡng.`);evidence.push({label:'Render pending',value:String(renderQueue)},{label:'Render failed',value:String(rf.length)},{label:'Publish pending',value:String(publishQueue)},{label:'Publish failed',value:String(pf.length)});if(rs)recommendations.push('Kiểm tra Stable Control và checkpoint trước khi Retry; không chạy worker thứ hai.');if(stuckPublish.length)recommendations.push('Kiểm tra Publish Worker và YouTube readiness trước khi retry job bị kẹt.');if(rf.length)recommendations.push('Đọc error/checkpoint của render job gần nhất rồi mới Retry.');if(pf.length)recommendations.push('Đọc lỗi provider trước khi Retry; không retry hàng loạt.');if(!recommendations.length)recommendations.push('Không phát hiện job kẹt hoặc failed.');
  }else if(intent==='youtube-live'){
    severity=ctx.deployment.youtubeLiveReady?'green':ctx.deployment.config.liveEnabled?'red':'yellow';findings.push(`YouTube configurationReady=${ctx.deployment.configurationReady?'YES':'NO'}, LIVE gate=${ctx.deployment.youtubeLiveReady?'READY':'LOCKED'}, privacy=${ctx.deployment.config.privacyStatus}.`);if(ctx.deployment.blockers.length)findings.push(`Blocker: ${ctx.deployment.blockers.join(' | ')}`);findings.push(`Private Test: ${ctx.deployment.privateTest.passed?'PASS':'CHƯA PASS'}.`);evidence.push({label:'YouTube LIVE',value:ctx.deployment.youtubeLiveReady?'READY':'LOCKED'},{label:'Private Test',value:ctx.deployment.privateTest.passed?'PASS':'NO'},{label:'Privacy',value:String(ctx.deployment.config.privacyStatus)});if(!ctx.deployment.configurationReady)recommendations.push('Hoàn tất OAuth/credential và TEST KẾT NỐI trước.');if(ctx.deployment.productionPrivacyNeedsPrivateTest&&!ctx.deployment.privateTest.passed)recommendations.push('Chạy Private Live Test thành công trước Public/Unlisted.');if(ctx.deployment.youtubeLiveReady)recommendations.push('Gate sẵn sàng; lần đầu vẫn nên thử Unlisted trước Public.');
  }else if(intent==='publish'){
    severity=m.publish.severity;findings.push(`Publish 7 ngày: ${a.kpis.publishPublished} thành công / ${a.kpis.publishFailed} failed, success ${pct(a.kpis.publishSuccessRate)}.`);findings.push(`Queue latency TB ${duration(publishLatency)}; pending ${publishQueue}; worker: ${m.publish.message}.`);evidence.push({label:'Publish success',value:pct(a.kpis.publishSuccessRate)},{label:'Queue latency',value:duration(publishLatency)},{label:'Pending',value:String(publishQueue)});if(m.publish.severity!=='green')recommendations.push('Xử lý worker/backlog hoặc job publishing bị kẹt trước khi tạo thêm live jobs.');if(a.kpis.publishSuccessRate!=null&&n(a.kpis.publishSuccessRate)<95)recommendations.push('Xem lỗi publish trong Audit/Queue, ưu tiên OAuth/network/provider.');if(!recommendations.length)recommendations.push('Publish pipeline hiện ổn; tiếp tục theo dõi success rate và latency.');
  }else if(intent==='resources'){
    severity=worst(m.memory.severity,m.cpu.severity,m.disk.severity);resources();findings.push(`Self-Heal: ${ctx.monitor.selfHealing.enabled?'ON':'OFF'}${ctx.monitor.selfHealing.autoPaused?' • AUTO-PAUSED':''}.`);recommendations.push('Giữ FFmpeg single worker, 720p mặc định và Node heap thấp.');recommendations.push('Không chạy local LLM lớn/Stable Diffusion cùng lúc với render trên máy 4 GB.');if(m.memory.severity!=='green')recommendations.push('Giảm dịch vụ đồng thời hoặc tăng swap; để Self-Heal bảo vệ Render Queue.');if(m.disk.severity!=='green')recommendations.push('Dọn output/backup theo retention trước khi tăng batch.');
  }else if(intent==='incidents'){
    const red=active.filter(x=>x.severity==='red'),yellow=active.filter(x=>x.severity==='yellow');severity=red.length?'red':yellow.length?'yellow':'green';findings.push(`Có ${active.length} incident active: ${red.length} RED, ${yellow.length} YELLOW.`);for(const x of active.slice(0,5))findings.push(`${x.component.toUpperCase()}: ${x.message}${x.acknowledged?' • ACK':''}${x.silenced?' • SILENCED':''}`);evidence.push({label:'Active incidents',value:String(active.length)},{label:'RED',value:String(red.length)},{label:'YELLOW',value:String(yellow.length)});recommendations.push(active.length?'ACK sau khi tiếp nhận; chỉ Silence khi có lý do vận hành rõ ràng.':'Không có incident active; tiếp tục monitor.');
  }else if(intent==='activity'){
    severity=ctx.monitor.overall;findings.push(`Có ${ctx.audit.length} sự kiện audit gần nhất.`);for(const x of ctx.audit.slice(0,6))findings.push(`${x.actor.label}: ${x.summary}`);recommendations.push('Đối chiếu Activity Timeline với thời điểm incident/KPI xấu đi.');
  }else{
    severity=ctx.monitor.overall;findings.push(`System Health ${ctx.monitor.overall.toUpperCase()}; ${active.length} incident active.`);findings.push(`7 ngày: render success ${pct(a.kpis.renderSuccessRate)}, publish success ${pct(a.kpis.publishSuccessRate)}.`);findings.push(`Queue: render ${renderQueue}, publish ${publishQueue}.`);evidence.push({label:'System',value:ctx.monitor.overall.toUpperCase()},{label:'Render success',value:pct(a.kpis.renderSuccessRate)},{label:'Publish success',value:pct(a.kpis.publishSuccessRate)});if(active.length)recommendations.push('Xử lý RED trước YELLOW; tránh tăng tải khi health chưa GREEN.');if(!ctx.deployment.youtubeLiveReady)recommendations.push('YouTube LIVE vẫn khóa; giữ Dry-run/Private cho đến khi readiness đạt.');if(!recommendations.length)recommendations.push('Hệ thống ổn; tiếp tục theo dõi KPI 7/30 ngày và Audit Timeline.');
  }
  return{mode:'rules',intent,severity,summary:findings[0]||'Không có dữ liệu đáng chú ý.',findings:uniq(findings),recommendations:uniq(recommendations),evidence:evidence.slice(0,8),generatedAt:new Date().toISOString(),readOnly:true};
}

function llmEnabled(){return process.env.OPS_ASSISTANT_LLM_ENABLED==='true'}
function llmProvider():LlmProvider|undefined{if(process.env.GEMINI_API_KEY?.trim())return{id:'gemini',url:`${(process.env.GEMINI_API_URL||'https://generativelanguage.googleapis.com/v1beta/openai').replace(/\/openai\/?$/,'')}/models/${encodeURIComponent(process.env.GEMINI_MODEL?.trim()||'gemini-2.5-flash')}:generateContent`,key:process.env.GEMINI_API_KEY.trim()};if(process.env.AI_API_URL?.trim()&&process.env.AI_API_KEY?.trim()&&process.env.AI_MODEL?.trim()){const base=process.env.AI_API_URL.trim().replace(/\/$/,'');return{id:'custom',url:/\/chat\/completions$/i.test(base)?base:`${base}/chat/completions`,key:process.env.AI_API_KEY.trim(),model:process.env.AI_MODEL.trim()}}}
async function enhance(question:string,base:OpsAssistantAnswer,ctx:Awaited<ReturnType<typeof opsAssistantContext>>):Promise<OpsAssistantAnswer>{
  const p=llmProvider();if(!llmEnabled()||!p)return base;const compact={question,base,monitor:{overall:ctx.monitor.overall,components:Object.fromEntries(Object.entries(ctx.monitor.components).map(([k,v]:any)=>[k,{severity:v.severity,message:v.message}]))},kpis:ctx.analytics7.kpis,activeIncidents:ctx.incidents.filter(x=>x.active).slice(0,8).map(x=>({component:x.component,severity:x.severity,message:x.message})),youtube:{ready:ctx.deployment.youtubeLiveReady,blockers:ctx.deployment.blockers}};const prompt='Bạn là trợ lý vận hành READ-ONLY cho Auto Media trên Dell Wyse 4GB. Chỉ phân tích dữ liệu cung cấp; không bịa, không yêu cầu/hiển thị secrets, không tuyên bố đã thực hiện hành động. Trả JSON {summary:string,findings:string[],recommendations:string[]} bằng tiếng Việt. DATA='+JSON.stringify(compact);
  try{let text='';if(p.id==='gemini'){const r=await fetch(p.url,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':p.key},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:0.1,maxOutputTokens:500,responseMimeType:'application/json'}}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`HTTP ${r.status}`);const d:any=await r.json();text=d?.candidates?.[0]?.content?.parts?.map((x:any)=>x.text||'').join('')||''}else{const r=await fetch(p.url,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${p.key}`},body:JSON.stringify({model:p.model,messages:[{role:'user',content:prompt}],temperature:0.1,max_tokens:500,response_format:{type:'json_object'}}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`HTTP ${r.status}`);const d:any=await r.json();text=String(d?.choices?.[0]?.message?.content||'')}const x=JSON.parse(text);return{...base,mode:'llm',provider:p.id,summary:String(x.summary||base.summary).slice(0,700),findings:uniq(Array.isArray(x.findings)?x.findings.map(String):base.findings),recommendations:uniq(Array.isArray(x.recommendations)?x.recommendations.map(String):base.recommendations)}}catch{return base}}

export async function answerOpsQuestion(ownerId:string,input:unknown){const q=question(input),ctx=await opsAssistantContext(ownerId);return enhance(q,rulesAnswer(q,ctx),ctx)}
export function opsAssistantStatus(){const p=llmProvider();return{enabled:true,readOnly:true,defaultMode:'rules',llmEnabled:llmEnabled(),llmConfigured:Boolean(p),provider:p?.id||null,maxQuestionChars:600,noSideEffects:true}}
