export type ScriptLength='30'|'60'|'90';
export type AiProvider='ollama'|'gemini'|'custom'|'rules';
export interface EditedNews{headline:string;hook:string;script:string;caption:string;hashtags:string[];estimatedSeconds:number;mode:'local'|'llm';provider:AiProvider;completeness:{complete:boolean;included:string[];missing:string[]};removedIllustrationText:number}
type ProviderConfig={id:Exclude<AiProvider,'rules'>;base:string;key?:string;model:string};

const targetWords:Record<ScriptLength,number>={30:78,60:145,90:215};
const HIGH=/\b(cảnh báo|khẩn|tin nóng|bất ngờ|đáng chú ý|mới nhất|nguy cơ|bão|lũ|cháy|tai nạn|sức khỏe|giá vàng|usd|chính sách|bhyt)\b/i;
const SENSITIVE=/\b(tử vong|thiệt mạng|thương vong|nạn nhân|trẻ em|ung thư|tự tử|thảm họa|chiến tranh)\b/i;
const IMAGE_LINE=/^(?:(?:ảnh|hình|video|clip)(?:\s+(?:minh\s*họa|tư\s*liệu|đính\s*kèm|chụp\s*màn\s*hình))?|minh\s*họa|nguồn\s*ảnh|photo|image|illustration|caption|credit|thumbnail)\s*(?::|[-–—]|\||©)/i;
const IMAGE_FILE=/\b[^\s/\\]+\.(?:jpe?g|png|webp|gif|bmp|svg|avif|heic)(?:\?[^\s]*)?\b/ig;
const CREDIT=/\((?:ảnh|hình|video|nguồn ảnh|photo|image|credit)\s*:[^)]+\)/ig;
function clean(s:string){return s.replace(/\s+/g,' ').trim()}
function words(s:string){return clean(s).split(/\s+/).filter(Boolean)}
function shorten(s:string,max:number){const w=words(s);return w.length<=max?clean(s):w.slice(0,max).join(' ').replace(/[,;:]$/,'')+'…'}
function sentences(s:string){return s.replace(/\n+/g,' ').split(/(?<=[.!?…])\s+/).map(clean).filter(x=>x.length>12)}
function norm(s:string){return clean(s).toLocaleLowerCase('vi-VN').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d')}
function tokens(s:string){return new Set(norm(s).split(/\s+/).filter(x=>x.length>3&&!['dang','duoc','nhung','nhieu','thong','dieu','chinh'].includes(x)))}
function similarity(a:string,b:string){const x=tokens(a),y=tokens(b);if(!x.size||!y.size)return 0;let same=0;for(const w of x)if(y.has(w))same++;return same/Math.min(x.size,y.size)}
function trimLead(s:string){return clean(s).replace(/^(đáng chú ý|tin nóng|tin mới|cảnh báo|mới nhất|thông tin mới)\s*[:：,!.-]*\s*/i,'')}
export function stripIllustrationText(value:string){let removed=0;const text=value.split(/\r?\n/).map(line=>{const t=line.trim();if(!t)return'';if(IMAGE_LINE.test(t)){removed++;return''}const f=t.match(IMAGE_FILE),c=t.match(CREDIT);removed+=(f?.length||0)+(c?.length||0);return t.replace(IMAGE_FILE,' ').replace(CREDIT,' ').replace(/\s{2,}/g,' ').trim()}).filter(Boolean).join('\n');return{text:text.trim(),removed}}

type Fact={key:string;label:string;text:string;priority:number};
const RULES:Array<[string,string,RegExp,number]>=[
 ['event','sự việc chính',/\b(xảy ra|cho biết|thông báo|công bố|quyết định|ghi nhận|phát hiện|đề xuất|ban hành|tăng|giảm|bắt giữ|cảnh báo|thiệt hại|tử vong)\b/i,10],
 ['result','kết quả/hệ quả',/\b(kết quả|hậu quả|khiến|dẫn đến|do đó|vì vậy|ảnh hưởng|thiệt hại|đã cứu|đang điều trị|xử lý)\b/i,9],
 ['time','thời gian',/\b(hôm nay|hôm qua|sáng|trưa|chiều|tối|đêm|ngày|tháng|năm|lúc)\b|\b\d{1,2}[\/-]\d{1,2}(?:[\/-]\d{2,4})?\b/i,8],
 ['place','địa điểm',/\b(tại|ở|thuộc|khu vực|tỉnh|thành phố|huyện|xã|phường|quốc gia|bệnh viện)\b/i,8],
 ['people','người/tổ chức liên quan',/\b(ông|bà|anh|chị|người|cơ quan|bộ|sở|công an|chính phủ|bệnh viện|công ty|đội|lực lượng)\b/i,7],
 ['number','số liệu quan trọng',/\b\d+(?:[.,]\d+)?\s*(?:%|triệu|tỷ|nghìn|người|ca|đồng|usd|km|giờ|phút)?\b/i,7],
 ['advice','khuyến cáo/cập nhật',/\b(khuyến cáo|cảnh báo|lưu ý|không nên|nên|tiếp tục|đang điều tra|đang xác minh|sẽ cập nhật)\b/i,6]
];
function facts(title:string,body:string){const ss=sentences(body),out:Fact[]=[];for(const[key,label,re,priority]of RULES){const text=ss.find(s=>re.test(s));if(text)out.push({key,label,text,priority})}if(!out.some(x=>x.key==='event'))out.unshift({key:'event',label:'sự việc chính',text:ss[0]||title,priority:10});return out.sort((a,b)=>b.priority-a.priority)}
function headline(title:string,_body:string){return shorten(trimLead(clean(title).replace(/^[\-–—:]+|[\-–—:]+$/g,'')),16).slice(0,125)}
function hook(title:string,body:string){const s=title+' '+body;if(/\b(sức khỏe|y tế|bệnh|dịch|virus|vaccine|vắc xin|thuốc|điều trị|bệnh viện|ung thư|tim mạch|đột quỵ|đái tháo đường|ngộ độc)\b/i.test(s)){if(/\b(cảnh báo|nguy cơ|tử vong|ngộ độc|bùng phát|thu hồi)\b/i.test(s))return'Đây là cảnh báo sức khỏe không nên bỏ qua.';return'Thông tin y tế mới có thể ảnh hưởng trực tiếp bạn.'}if(SENSITIVE.test(s))return'Diễn biến mới này đang khiến dư luận quan tâm.';if(/\b(trump|fed|lãi suất)\b/i.test(s))return'Sức ép lên Fed vừa được đẩy lên mức mới.';if(/\b(usd|giá vàng|thị trường|chứng khoán)\b/i.test(s))return'Một tín hiệu mới đang khiến thị trường đổi nhịp.';if(/\b(cảnh báo|nguy cơ|bão|lũ|cháy|sạt lở)\b/i.test(s))return'Nguy cơ mới đang hiện hữu và không thể xem nhẹ.';if(/\b(chính sách|quy định|bhyt|mức đóng)\b/i.test(s))return'Một thay đổi mới có thể ảnh hưởng trực tiếp nhiều người.';const first=sentences(body)[0]||trimLead(title),candidate=shorten(trimLead(first),11);return similarity(candidate,title)>.72?'Câu chuyện vừa xuất hiện một diễn biến hoàn toàn mới.':candidate.replace(/[,:;]$/,'')+'.'}
function vary(text:string,previous:string){let s=text;if(/sức ép/i.test(previous))s=s.replace(/(?:nhằm\s+)?gây sức ép (?:lên|với)/i,'nhằm buộc').replace(/sức ép (?:lên|với)/i,'tác động tới');if(/ảnh hưởng/i.test(previous))s=s.replace(/(?:gây|chịu|bị)?\s*ảnh hưởng/i,'chịu tác động');if(/nguy cơ/i.test(previous))s=s.replace(/nguy cơ/i,'rủi ro');if(/thay đổi/i.test(previous))s=s.replace(/thay đổi/i,'điều chỉnh');return clean(s)}
function compact(open:string,fs:Fact[],max:number,source?:string,avoid=''){const parts:string[]=[],seen=new Set<string>();let used=words(open).length;for(const f of fs){if(seen.has(f.text)||similarity(f.text,open)>.72||similarity(f.text,avoid)>.82)continue;seen.add(f.text);const varied=vary(f.text,open+' '+parts.join(' ')),left=max-used;if(left<8)break;const p=shorten(varied,Math.min(words(varied).length,left));parts.push(p);used+=words(p).length}const tail=source?' Theo '+clean(source)+'.':'';return shorten(clean(open+' '+parts.join(' ')+tail),max)}
function deDuplicate(head:string,open:string,script:string){let s=clean(script);const hs=sentences(s);if(hs.length&&similarity(hs[0],head)>.72)hs.shift();if(hs.length&&similarity(hs[0],open)>.72)hs.shift();s=hs.join(' ');return clean(open+' '+s)}
function audit(script:string,fs:Fact[]){const n=norm(script),included=fs.filter(f=>norm(f.text).split(/\s+/).filter(x=>x.length>4).slice(0,6).some(x=>n.includes(x))).map(f=>f.label),required=[...new Set(fs.filter(f=>f.priority>=8).map(f=>f.label))],missing=required.filter(x=>!included.includes(x));return{complete:missing.length===0,included:[...new Set(included)],missing}}
function localEdit(input:{title:string;body:string;sourceName?:string;length:ScriptLength}):EditedNews{const t=stripIllustrationText(input.title),b=stripIllustrationText(input.body),title=t.text||'Bản tin mới',body=b.text,fs=facts(title,body),h=headline(title,body),hk=hook(title,body),script=compact(hk,fs,targetWords[input.length],input.sourceName,h),source=input.sourceName?' Nguồn: '+clean(input.sourceName)+'.':'';return{headline:h,hook:hk,script,caption:shorten(h+'.'+source+' Theo dõi VietNewsFlow AI để cập nhật diễn biến mới.',50),hashtags:['#VietNewsFlowAI',HIGH.test(title+' '+body)?'#TinDangChuY':'#TinMoi','#CapNhat'],estimatedSeconds:Number(input.length),mode:'local',provider:'rules',completeness:audit(script,fs),removedIllustrationText:t.removed+b.removed}}

function providers():ProviderConfig[]{const out:ProviderConfig[]=[];if(/^true$/i.test(process.env.OLLAMA_ENABLED||'')&&process.env.OLLAMA_MODEL?.trim())out.push({id:'ollama',base:(process.env.OLLAMA_API_URL||'http://host.docker.internal:11434/v1').replace(/\/$/,''),key:process.env.OLLAMA_API_KEY||'ollama',model:process.env.OLLAMA_MODEL.trim()});if(process.env.AI_API_URL?.trim()&&process.env.AI_API_KEY?.trim()&&process.env.AI_MODEL?.trim())out.push({id:'custom',base:process.env.AI_API_URL.trim().replace(/\/$/,''),key:process.env.AI_API_KEY.trim(),model:process.env.AI_MODEL.trim()});if(process.env.GEMINI_API_KEY?.trim()&&process.env.GEMINI_MODEL?.trim())out.push({id:'gemini',base:(process.env.GEMINI_API_URL||'https://generativelanguage.googleapis.com/v1beta/openai').replace(/\/$/,''),key:process.env.GEMINI_API_KEY.trim(),model:process.env.GEMINI_MODEL.trim()});return out}
function endpoint(base:string){return /\/chat\/completions$/i.test(base)?base:base+'/chat/completions'}
export function aiEditorStatus(){const configured=providers();return{enabled:configured.length>0,order:configured.map(x=>x.id),providers:configured.map(x=>({id:x.id,model:x.model,endpoint:x.base,hasKey:Boolean(x.key)})),fallback:'rules'}}
export async function testAiEditor(){const ps=providers();if(!ps.length)return{ok:false,...aiEditorStatus(),error:'Chưa cấu hình Ollama, Gemini hoặc AI_API'};const errors:string[]=[];for(const p of ps){try{const r=await fetch(endpoint(p.base),{method:'POST',headers:{'content-type':'application/json',...(p.key?{authorization:'Bearer '+p.key}:{})},body:JSON.stringify({model:p.model,messages:[{role:'user',content:'Chỉ trả lời JSON: {"ok":true}'}],temperature:0,max_tokens:20,response_format:{type:'json_object'}}),signal:AbortSignal.timeout(p.id==='ollama'?60000:20000)});if(r.ok)return{ok:true,provider:p.id,model:p.model,order:ps.map(x=>x.id)};errors.push(`${p.id}: HTTP ${r.status}`)}catch(e){errors.push(`${p.id}: ${e instanceof Error?e.message:String(e)}`)}}return{ok:false,...aiEditorStatus(),errors}}

async function llmEdit(input:{title:string;body:string;sourceName?:string;length:ScriptLength},provider:ProviderConfig):Promise<EditedNews>{
 const t=stripIllustrationText(input.title),b=stripIllustrationText(input.body),fs=facts(t.text,b.text),check=fs.map(x=>'- '+x.label+': '+x.text).join('\n');
 const prompt=`Bạn là biên tập viên phát thanh và video tin tức tiếng Việt chuyên nghiệp, ưu tiên lĩnh vực sức khỏe và có tư duy truyền thông y khoa dựa trên bằng chứng. Viết kịch bản khoảng ${input.length} giây, hấp dẫn nhưng chính xác.\nQUY TẮC 3 GIÂY ĐẦU: hook chỉ 6-12 từ, đi thẳng vào xung đột, thay đổi hoặc hệ quả đáng chú ý nhất; không chào hỏi, không nói “đáng chú ý”, “tin nóng”, “bản tin sau đây”; không đọc lại hay diễn đạt gần giống headline.\nHeadline chỉ dùng để hiển thị, KHÔNG được chép headline vào script. Script bắt đầu đúng một lần bằng hook, câu kế tiếp phải bổ sung thông tin mới. Không lặp câu, lặp ý hoặc lặp liên tiếp tên nhân vật. Thay đổi cấu trúc và từ nối tự nhiên như “trong khi đó”, “tuy nhiên”, “đáng lưu ý”, “theo báo cáo”, nhưng không dùng một cụm máy móc nhiều lần.\nBảo toàn sự việc, người/tổ chức, thời gian, địa điểm, diễn biến, số liệu, kết quả/hệ quả và khuyến cáo có trong nguồn. Rút gọn bằng cách gộp câu và bỏ từ thừa, không bỏ dữ kiện. Không thêm hoặc suy diễn thông tin. Không đưa tên file/chú thích/credit ảnh vào bất kỳ trường nào. Với tin sức khỏe: phân biệt nguy cơ tương đối và tuyệt đối; không biến liên quan thành quan hệ nhân quả; không khẳng định chẩn đoán hay hiệu quả điều trị quá mức; giữ liều lượng, đối tượng, chống chỉ định và khuyến cáo cấp cứu nếu nguồn có; ưu tiên WHO, CDC, FDA, cơ quan y tế và nghiên cứu gốc. Tin nhạy cảm phải tôn trọng, không giật gân. Headline 8-16 từ.\nTrả JSON thuần: headline, hook, script, caption, hashtags (3-5 phần tử). Trường script phải gồm hook đúng một lần.\nDỮ KIỆN PHẢI GIỮ:\n${check}\nTIÊU ĐỀ: ${t.text}\nNGUỒN: ${input.sourceName||''}\nNỘI DUNG:\n${b.text.slice(0,9000)}`;
 const r=await fetch(endpoint(provider.base),{method:'POST',headers:{'content-type':'application/json',...(provider.key?{'authorization':'Bearer '+provider.key}:{})},body:JSON.stringify({model:provider.model,messages:[{role:'user',content:prompt}],temperature:.25,response_format:{type:'json_object'}}),signal:AbortSignal.timeout(provider.id==='ollama'?120000:45000)});if(!r.ok)throw Error('HTTP '+r.status);const data:any=await r.json(),raw=data?.choices?.[0]?.message?.content;if(!raw)throw Error('Phản hồi không có nội dung');const x=JSON.parse(String(raw).replace(/^```(?:json)?\s*|\s*```$/gi,'').trim());
 const eh=stripIllustrationText(String(x.headline||'')),ek=stripIllustrationText(String(x.hook||'')),es=stripIllustrationText(String(x.script||'')),ec=stripIllustrationText(String(x.caption||''));const finalHeadline=clean(eh.text||headline(t.text,b.text)).slice(0,125);let finalHook=shorten(trimLead(ek.text||hook(t.text,b.text)),12);if(similarity(finalHook,finalHeadline)>.7)finalHook=hook(t.text,b.text);let script=shorten(deDuplicate(finalHeadline,finalHook,es.text),targetWords[input.length]),completeness=audit(script,fs);if(!completeness.complete){script=compact(finalHook,fs,targetWords[input.length],input.sourceName,finalHeadline);completeness=audit(script,fs)}
 return{headline:finalHeadline,hook:finalHook,script,caption:clean(ec.text),hashtags:Array.isArray(x.hashtags)?x.hashtags.map((v:any)=>clean(String(v))).filter(Boolean).slice(0,5):['#VietNewsFlowAI','#TinDangChuY','#CapNhat'],estimatedSeconds:Number(input.length),mode:'llm',provider:provider.id,completeness,removedIllustrationText:t.removed+b.removed+eh.removed+ek.removed+es.removed+ec.removed}
}
export async function editNews(input:{title:string;body:string;sourceName?:string;length:ScriptLength}){for(const p of providers()){try{return await llmEdit(input,p)}catch(e){console.warn(`AI editor ${p.id} failed; trying next provider:`,e)}}console.warn('AI editor using final rules fallback');return localEdit(input)}
