import { randomUUID } from 'node:crypto';
import { db,all,run } from '../storage/db.js';

export type HookStrategy='direct'|'question'|'number'|'human'|'contrast'|'consequence'|'timeline'|'explainer'|'alert';
export interface EditorialPerformanceInput{ownerId:string;storyId?:string;platform:string;hookStrategy:HookStrategy;angle:string;durationSeconds:number;impressions?:number;views?:number;retention3s?:number;retention10s?:number;completionRate?:number;shareRate?:number;commentRate?:number}

db.exec(`CREATE TABLE IF NOT EXISTS editorial_hook_history(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,hook TEXT NOT NULL,strategy TEXT NOT NULL,angle TEXT,story_id TEXT,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_editorial_hook_owner_created ON editorial_hook_history(owner_id,created_at DESC);
CREATE TABLE IF NOT EXISTS editorial_performance(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,story_id TEXT,platform TEXT NOT NULL,hook_strategy TEXT NOT NULL,angle TEXT,duration_seconds INTEGER NOT NULL,impressions INTEGER,views INTEGER,retention_3s REAL,retention_10s REAL,completion_rate REAL,share_rate REAL,comment_rate REAL,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_editorial_perf_owner_created ON editorial_performance(owner_id,created_at DESC);
CREATE TABLE IF NOT EXISTS editorial_story_runs(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,title TEXT NOT NULL,angle TEXT NOT NULL,hook_strategy TEXT NOT NULL,hook TEXT NOT NULL,requested_duration TEXT NOT NULL,selected_duration INTEGER NOT NULL,quality_score INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_editorial_story_owner_created ON editorial_story_runs(owner_id,created_at DESC);`);


export interface EditorialStoryRunInput{ownerId:string;title:string;angle:string;hookStrategy:HookStrategy;hook:string;requestedDuration:string;selectedDuration:number;qualityScore:number}
export function registerEditorialStoryRun(x:EditorialStoryRunInput){const id=randomUUID();run('INSERT INTO editorial_story_runs(id,owner_id,title,angle,hook_strategy,hook,requested_duration,selected_duration,quality_score,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',id,x.ownerId,x.title,x.angle,x.hookStrategy,x.hook,x.requestedDuration,x.selectedDuration,x.qualityScore,new Date().toISOString());return id}
export function editorialStoryRun(ownerId:string,storyId:string){return all<any>('SELECT id,owner_id,title,angle,hook_strategy,hook,requested_duration,selected_duration,quality_score,created_at FROM editorial_story_runs WHERE owner_id=? AND id=? LIMIT 1',ownerId,storyId)[0]}
export function recordEditorialPerformanceForStory(x:{ownerId:string;storyId:string;platform:string;durationSeconds?:number;impressions?:number;views?:number;retention3s?:number;retention10s?:number;completionRate?:number;shareRate?:number;commentRate?:number}){const story=editorialStoryRun(x.ownerId,x.storyId);if(!story)throw new Error('Editorial story không tồn tại hoặc không thuộc owner hiện tại');recordEditorialPerformance({ownerId:x.ownerId,storyId:x.storyId,platform:x.platform,hookStrategy:story.hook_strategy as HookStrategy,angle:String(story.angle),durationSeconds:x.durationSeconds||Number(story.selected_duration)||60,impressions:x.impressions,views:x.views,retention3s:x.retention3s,retention10s:x.retention10s,completionRate:x.completionRate,shareRate:x.shareRate,commentRate:x.commentRate})}

export function recentHooks(ownerId:string,limit=60){return all<{hook:string;strategy:HookStrategy;angle?:string}>('SELECT hook,strategy,angle FROM editorial_hook_history WHERE owner_id=? ORDER BY created_at DESC LIMIT ?',ownerId,Math.max(1,Math.min(200,limit)))}
export function rememberHook(ownerId:string,hook:string,strategy:HookStrategy,angle?:string,storyId?:string){run('INSERT INTO editorial_hook_history(id,owner_id,hook,strategy,angle,story_id,created_at) VALUES(?,?,?,?,?,?,?)',randomUUID(),ownerId,hook,strategy,angle||null,storyId||null,new Date().toISOString())}
export function recordEditorialPerformance(x:EditorialPerformanceInput){run(`INSERT INTO editorial_performance(id,owner_id,story_id,platform,hook_strategy,angle,duration_seconds,impressions,views,retention_3s,retention_10s,completion_rate,share_rate,comment_rate,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,randomUUID(),x.ownerId,x.storyId||null,x.platform,x.hookStrategy,x.angle,x.durationSeconds,x.impressions??null,x.views??null,x.retention3s??null,x.retention10s??null,x.completionRate??null,x.shareRate??null,x.commentRate??null,new Date().toISOString())}
function metricScore(r:any){const completion=Math.max(0,Math.min(1,Number(r.completion_rate)||0)),r3=Math.max(0,Math.min(1,Number(r.retention_3s)||0)),r10=Math.max(0,Math.min(1,Number(r.retention_10s)||0)),share=Math.max(0,Math.min(.2,Number(r.share_rate)||0))/.2;return completion*.4+r3*.25+r10*.2+share*.15}
export function editorialLearningProfile(ownerId:string){const rows=all<any>('SELECT hook_strategy,angle,completion_rate,retention_3s,retention_10s,share_rate FROM editorial_performance WHERE owner_id=? ORDER BY created_at DESC LIMIT 500',ownerId),groups=new Map<string,{n:number,total:number}>();for(const r of rows){const key=String(r.hook_strategy||'direct'),g=groups.get(key)||{n:0,total:0};g.n++;g.total+=metricScore(r);groups.set(key,g)}const strategyBoost:Record<string,number>={};for(const[k,g]of groups)strategyBoost[k]=g.n>=3?Math.round(((g.total/g.n)-.5)*20):0;return{samples:rows.length,strategyBoost,bestStrategies:[...groups.entries()].filter(([,g])=>g.n>=3).sort((a,b)=>b[1].total/b[1].n-a[1].total/a[1].n).slice(0,3).map(([strategy,g])=>({strategy,samples:g.n,score:Number((g.total/g.n).toFixed(3))}))}}
export function editorialLearningStats(ownerId:string){const hooks=all<any>('SELECT COUNT(*) n FROM editorial_hook_history WHERE owner_id=?',ownerId)[0]?.n||0,perf=all<any>('SELECT COUNT(*) n FROM editorial_performance WHERE owner_id=?',ownerId)[0]?.n||0,stories=all<any>('SELECT COUNT(*) n FROM editorial_story_runs WHERE owner_id=?',ownerId)[0]?.n||0;return{hooks:Number(hooks),storyRuns:Number(stories),performanceSamples:Number(perf),profile:editorialLearningProfile(ownerId)}}
