import type { StoryBlueprint } from './newsroom.js';

export interface EditorialQualityReport{score:number;ready:boolean;claimCoverage:number;missingMandatory:string[];redundancyScore:number;endingComplete:boolean;spokenVietnameseScore:number;issues:string[];recommendations:string[]}
const clean=(s:string)=>s.replace(/\s+/g,' ').trim();
const norm=(s:string)=>clean(s).toLocaleLowerCase('vi-VN').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9\s]/g,' ');
const tokens=(s:string)=>new Set(norm(s).split(/\s+/).filter(x=>x.length>3));
function overlap(a:string,b:string){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let same=0;for(const x of A)if(B.has(x))same++;return same/Math.min(A.size,B.size)}
function scriptSentences(s:string){return clean(s).split(/(?<=[.!?])\s+/).map(clean).filter(x=>x.length>8)}
function redundancy(sentences:string[]){let max=0;for(let i=0;i<sentences.length;i++)for(let j=i+1;j<sentences.length;j++)max=Math.max(max,overlap(sentences[i],sentences[j]));return max}
function endingComplete(script:string){const s=clean(script);return Boolean(s)&&/[.!?]$/.test(s)&&!/(?:và|nhưng|vì|do|khi|nếu|trong khi|theo|với|của)\s*[.!?]?$/i.test(s)&&!s.endsWith('…')}
function spokenScore(script:string){const ss=scriptSentences(script);if(!ss.length)return 0;let score=100;for(const s of ss){const n=s.split(/\s+/).length;if(n>32)score-=Math.min(12,n-32);if((s.match(/,/g)||[]).length>4)score-=5;if(/\b[A-Z]{5,}\b/.test(s))score-=3}return Math.max(0,Math.round(score))}
export function evaluateEditorialQuality(script:string,b:StoryBlueprint):EditorialQualityReport{const issues:string[]=[],recommendations:string[]=[],mandatory=b.rankedClaims.filter(x=>b.requiredClaimIds.includes(x.claimId)),covered=mandatory.filter(x=>overlap(script,x.fact.text)>=.42),missingMandatory=mandatory.filter(x=>!covered.includes(x)).map(x=>x.claimId),claimCoverage=mandatory.length?Math.round(covered.length/mandatory.length*100):100,ss=scriptSentences(script),redundancyScore=Math.round(redundancy(ss)*100),ending=endingComplete(script),spokenVietnameseScore=spokenScore(script);if(missingMandatory.length){issues.push(`Thiếu ${missingMandatory.length} claim bắt buộc`);recommendations.push('Bổ sung claim bắt buộc trước khi finalize.')}if(redundancyScore>=72){issues.push('Lặp ý/cấu trúc cao');recommendations.push('Gộp hoặc viết lại các câu có nghĩa gần nhau.')}if(!ending){issues.push('Kết thúc chưa trọn nghĩa');recommendations.push('Thay câu cuối bằng một câu hoàn chỉnh, không cắt cơ học.')}if(spokenVietnameseScore<82){issues.push('Câu đọc thành tiếng còn nặng');recommendations.push('Tách câu dài, giảm chuỗi mệnh đề và acronym.')}const score=Math.max(0,Math.round(claimCoverage*.42+(100-redundancyScore)*.18+(ending?100:45)*.18+spokenVietnameseScore*.22)),ready=missingMandatory.length===0&&ending&&redundancyScore<78&&score>=82;return{score,ready,claimCoverage,missingMandatory,redundancyScore,endingComplete:ending,spokenVietnameseScore,issues,recommendations}}
export function editorialCritic(script:string,b:StoryBlueprint){const q=evaluateEditorialQuality(script,b),notes=[...q.issues];if(b.angle==='direct'&&scriptSentences(script).length<3)notes.push('Bản tin quá mỏng so với góc direct news.');if(b.complexity==='high'&&script.split(/\s+/).length<140)notes.push('Nguồn phức tạp nhưng kịch bản quá ngắn; nên dùng 90–120 giây.');return{...q,criticNotes:notes}}
