import type { StoryBlueprint, RankedClaim } from './newsroom.js';
import type { HookStrategy } from './editorial-learning.js';

export interface HookCandidate{strategy:HookStrategy;text:string;origin:'rules'|'ai';truth:number;novelty:number;relevance:number;clarity:number;retention:number;clickbaitRisk:number;similarity:number;finalScore:number}
const norm=(s:string)=>s.toLocaleLowerCase('vi-VN').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const tokenSet=(s:string)=>new Set(norm(s).split(' ').filter(x=>x.length>2));
export function hookSimilarity(a:string,b:string){const A=tokenSet(a),B=tokenSet(b);if(!A.size||!B.size)return 0;let inter=0;for(const t of A)if(B.has(t))inter++;const j=inter/(A.size+B.size-inter),pa=norm(a).split(' ').slice(0,4).join(' '),pb=norm(b).split(' ').slice(0,4).join(' ');return Math.min(1,j+(pa && pa===pb ? .35 : 0))}
function sentenceCore(text:string,max=20){let s=text.trim().replace(/\s+/g,' '),clause=s.split(/[,;](?=\s)/)[0];if(clause.split(/\s+/).length>=7)s=clause;const w=s.split(/\s+/);if(w.length>max)s=w.slice(0,max).join(' ');return s.replace(/[,:;.!?]+$/,'').trim()}
function byKind(claims:RankedClaim[],kind:string){return claims.find(x=>x.fact.kind===kind&&x.fact.support!=='uncertain')}
function make(strategy:HookStrategy,b:StoryBlueprint):string{const top=b.rankedClaims[0],event=byKind(b.rankedClaims,'event')||top,num=byKind(b.rankedClaims,'number'),effect=byKind(b.rankedClaims,'effect'),cause=byKind(b.rankedClaims,'cause'),person=byKind(b.rankedClaims,'person'),time=byKind(b.rankedClaims,'time'),advice=byKind(b.rankedClaims,'advice');switch(strategy){case'number':return sentenceCore(num?.fact.text||event?.fact.text||b.title,16);case'human':return person?`Điều đang xảy ra với ${sentenceCore(person.fact.text,15)}`:sentenceCore(event?.fact.text||b.title,16);case'consequence':return sentenceCore(effect?.fact.text||event?.fact.text||b.title,18);case'timeline':return time?`Mốc thời gian làm thay đổi diễn biến: ${sentenceCore(time.fact.text,13)}`:sentenceCore(event?.fact.text||b.title,16);case'explainer':return cause?`Vì sao chuyện này xảy ra? ${sentenceCore(cause.fact.text,12)}`:'Vì sao diễn biến này đáng quan tâm?';case'contrast':return effect&&cause?`${sentenceCore(cause.fact.text,9)}, nhưng hệ quả mới là điểm cần nhìn kỹ`:sentenceCore(event?.fact.text||b.title,16);case'alert':return advice?`Điều cần lưu ý ngay: ${sentenceCore(advice.fact.text,12)}`:sentenceCore(effect?.fact.text||event?.fact.text||b.title,16);case'question':return b.centralQuestion.replace(/[.!]+$/,'?');default:return sentenceCore(event?.fact.text||b.title,18)}}
const CLICKBAIT=/\b(sốc|kinh hoàng|không thể tin|gây sốc|chấn động|bí mật|khủng khiếp)\b/i;
const risky=(s:string)=>CLICKBAIT.test(s)?45:/\b(khẩn|nguy hiểm)\b/i.test(s)?14:0;
function relevance(strategy:HookStrategy,b:StoryBlueprint){if(strategy==='number'&&byKind(b.rankedClaims,'number'))return 96;if(strategy==='human'&&byKind(b.rankedClaims,'person'))return 92;if(strategy==='consequence'&&byKind(b.rankedClaims,'effect'))return 96;if(strategy==='explainer'&&byKind(b.rankedClaims,'cause'))return 95;if(strategy==='timeline'&&byKind(b.rankedClaims,'time'))return 91;if(strategy==='alert'&&byKind(b.rankedClaims,'advice'))return 92;if(strategy==='question')return 88;return 84}
function numericSafe(text:string,b:StoryBlueprint){const allowed=new Set((b.title+' '+b.rankedClaims.map(x=>x.fact.text).join(' ')).match(/\d+(?:[.,]\d+)?/g)||[]);return(text.match(/\d+(?:[.,]\d+)?/g)||[]).every(x=>allowed.has(x))}
function score(strategy:HookStrategy,text:string,origin:'rules'|'ai',b:StoryBlueprint,recent:Array<{hook:string}>,boost:Record<string,number>){const similarity=Math.max(0,...recent.map(x=>hookSimilarity(text,x.hook))),novelty=Math.round((1-similarity)*100),rel=relevance(strategy,b),truth=numericSafe(text,b)?98:55,clarity=Math.max(60,100-Math.max(0,text.split(/\s+/).length-18)*3),retention=Math.min(98,76+(strategy==='question'||strategy==='consequence'?12:strategy==='number'?10:strategy==='human'?8:origin==='ai'?6:4)),clickbaitRisk=risky(text),finalScore=Math.round(truth*.25+novelty*.22+rel*.22+clarity*.13+retention*.18-clickbaitRisk*.35+Number(boost[strategy]||0));return{strategy,text,origin,truth,novelty,relevance:rel,clarity,retention,clickbaitRisk,similarity:Number(similarity.toFixed(3)),finalScore} satisfies HookCandidate}
export function buildHookStudio(input:{blueprint:StoryBlueprint;recentHooks?:Array<{hook:string}>;strategyBoost?:Record<string,number>;aiCandidates?:Array<{strategy:HookStrategy;text:string}>}){const strategies:HookStrategy[]=['direct','question','number','human','contrast','consequence','timeline','explainer','alert'],recent=input.recentHooks||[],boost=input.strategyBoost||{},seen=new Set<string>(),out:HookCandidate[]=[];for(const strategy of strategies){const text=make(strategy,input.blueprint).replace(/\s+/g,' ').trim();if(text.length>=12&&!seen.has(norm(text))){seen.add(norm(text));out.push(score(strategy,text,'rules',input.blueprint,recent,boost))}}for(const x of input.aiCandidates||[]){const text=String(x.text||'').replace(/\s+/g,' ').trim(),n=norm(text);if(text.split(/\s+/).length<5||text.split(/\s+/).length>20||seen.has(n)||CLICKBAIT.test(text)||!numericSafe(text,input.blueprint))continue;seen.add(n);out.push(score(x.strategy,text,'ai',input.blueprint,recent,boost))}out.sort((a,b)=>b.finalScore-a.finalScore);return{selected:out.find(x=>x.similarity<.72&&x.clickbaitRisk<30&&x.truth>=90)||out[0],candidates:out.slice(0,8)}}
