import type { AudienceProfile, StoryBlueprint } from './newsroom.js';
import type { MasterStory, ScriptVersion } from './master-script.js';

export type EditorialPlatform='master'|'youtube'|'facebook'|'tiktok'|'zalo';
export interface PlatformEditorial{platform:EditorialPlatform;audience:AudienceProfile;script:string;claimIds:string[];seconds:number;captionHint:string;notes:string[]}
function audienceNote(a:AudienceProfile){switch(a){case'medical':return'Ưu tiên thuật ngữ chính xác, không đơn giản hóa quá mức.';case'investor':return'Ưu tiên cơ chế, số liệu và tác động thị trường.';case'patient':return'Ưu tiên điều người bệnh cần hiểu và hành động an toàn.';case'social':return'Ưu tiên câu ngắn, trực tiếp, dễ nghe trên điện thoại.';default:return'Ưu tiên rõ ràng, trung tính và dễ hiểu cho công chúng.'}}
function platformNote(p:EditorialPlatform){switch(p){case'youtube':return'Giữ nhịp giải thích và bối cảnh, không hy sinh claim bắt buộc.';case'facebook':return'Ưu tiên 45–90 giây và một luận điểm chính.';case'tiktok':return'Ưu tiên 30–60 giây; nếu claim bắt buộc không đủ chỗ phải dùng bản dài hơn.';case'zalo':return'Ưu tiên câu ngắn, thông tin thực dụng và nguồn rõ.';default:return'Bản master làm nguồn duy nhất cho mọi biến thể.'}}
export function adaptEditorialPlatform(input:{platform:EditorialPlatform;audience?:AudienceProfile;blueprint:StoryBlueprint;master:MasterStory;version:ScriptVersion}){const audience=input.audience||input.blueprint.audience,notes=[audienceNote(audience),platformNote(input.platform)];return{platform:input.platform,audience,script:input.version.script,claimIds:[...input.version.claimIds],seconds:input.version.estimatedSeconds,captionHint:input.platform==='zalo'?'Tóm tắt 2–4 câu kèm nguồn.':'Không lặp nguyên Hook trong caption.',notes} satisfies PlatformEditorial}
export function verifyPlatformClaimConsistency(masterClaimIds:string[],outputs:PlatformEditorial[],requiredClaimIds:string[]=[]){const master=new Set(masterClaimIds),required=new Set(requiredClaimIds),violations:string[]=[],missingRequired:Record<string,string[]>={};for(const o of outputs){for(const id of o.claimIds)if(!master.has(id))violations.push(`${o.platform}:${id}`);const have=new Set(o.claimIds),missing=[...required].filter(id=>!have.has(id));if(missing.length)missingRequired[o.platform]=missing}return{ok:violations.length===0&&Object.keys(missingRequired).length===0,violations,missingRequired}}
