const base=String(process.env.PROD_CHECK_URL||'http://127.0.0.1:8787').replace(/\/$/,'');
const apiKey=String(process.env.RENDER_API_KEY||'').trim();
const strict=process.env.PROD_CHECK_STRICT==='true';
const timeoutMs=Math.max(1000,Number(process.env.PROD_CHECK_TIMEOUT_MS||5000));

async function request(path,authenticated=false){
  const headers={accept:'application/json'};
  if(authenticated&&apiKey)headers.authorization=`Bearer ${apiKey}`;
  const r=await fetch(`${base}${path}`,{headers,signal:AbortSignal.timeout(timeoutMs)});
  const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{}
  if(!r.ok)throw new Error(`${path} -> HTTP ${r.status}: ${String(data.error||text||'unknown').slice(0,300)}`);return data;
}
function line(label,ok,detail=''){console.log(`${ok?'✓':'✗'} ${label}${detail?`: ${detail}`:''}`)}
try{
  const health=await request('/health');if(!health.ok)throw new Error('/health did not return ok=true');line('Service health',true,`${health.service||'auto-media'} / ${health.storage||'storage unknown'}`);
  if(!apiKey){line('Authenticated production checks',false,'skipped because RENDER_API_KEY is not set locally');if(strict)throw new Error('PROD_CHECK_STRICT=true requires RENDER_API_KEY');process.exit(0)}
  const monitoring=await request('/api/admin/monitoring',true),snapshot=monitoring.snapshot||{},overall=String(snapshot.overall||'unknown');line('Production monitor',overall!=='red',overall.toUpperCase());
  const components=snapshot.components||{};for(const name of ['memory','cpu','disk','render','publish','youtube']){const c=components[name];if(c?.severity&&c.severity!=='green')console.log(`  ${name}: ${String(c.severity).toUpperCase()} • ${c.message||''}`)}
  const activeIncidents=Array.isArray(monitoring.incidents)?monitoring.incidents.filter(x=>x.active):[];if(activeIncidents.length){const acked=activeIncidents.filter(x=>x.acknowledged).length,silenced=activeIncidents.filter(x=>x.silenced).length;console.log(`  Active incidents: ${activeIncidents.length} • ACK ${acked} • silenced ${silenced}`)}
  const maintenance=monitoring.maintenance||snapshot.maintenance||{};line('Maintenance window',true,maintenance.active?`ACTIVE until ${maintenance.endsAt||'?'} • ${maintenance.reason||'maintenance'}`:'OFF');
  const selfHeal=snapshot.selfHealing||{};line('Safe self-heal',selfHeal.enabled!==false,selfHeal.enabled===false?'OFF':selfHeal.autoPaused?`AUTO-PAUSED • green ${selfHeal.greenCycles||0}/${selfHeal.requiredGreen||3}`:'ON');
  const alerting=snapshot.alerting||{},channels=alerting.channels||{},enabledChannels=[channels.webhook?'webhook':'',channels.telegram?'telegram':'',channels.email?'email':''].filter(Boolean);line('External alerts',Boolean(alerting.enabled),alerting.enabled?`${enabledChannels.join(', ')} • min ${String(alerting.minSeverity||'red').toUpperCase()}${maintenance.active?' • MUTED BY MAINTENANCE':''}`:'not configured');
  const audit=await request('/api/admin/audit?limit=1',true);line('Operator audit trail',Boolean(audit.stats),audit.stats?`${audit.stats.total||0} events • retention ${audit.stats.retentionDays||90}d`:'unavailable');
  const analytics=await request('/api/admin/analytics?days=7',true),k=analytics.kpis||{};line('Production analytics',Boolean(analytics.period&&analytics.daily),analytics.period?`7d • render OK ${k.videosReady||0} • publish OK ${k.publishPublished||0}`:'unavailable');
  const ops=await request('/api/admin/ops-assistant/status',true);line('AI operations assistant',Boolean(ops.readOnly&&ops.noSideEffects),`${ops.defaultMode||'rules'} • read-only${ops.llmEnabled&&ops.llmConfigured?` • LLM ${ops.provider||'configured'}`:''}`);
  const deployment=await request('/api/publish-deployment-readiness',true);line('Publisher configuration',Boolean(deployment.configurationReady),deployment.configurationReady?'configured':'not complete');line('YouTube production gate',Boolean(deployment.youtubeLiveReady),deployment.youtubeLiveReady?'READY':'LOCKED');
  const blockers=Array.isArray(deployment.blockers)?deployment.blockers:[];if(blockers.length)console.log(`  Blockers: ${blockers.join(' | ')}`);const warnings=Array.isArray(deployment.warnings)?deployment.warnings:[];if(warnings.length)console.log(`  Warnings: ${warnings.join(' | ')}`);const privacy=deployment.config?.privacyStatus;if(privacy)console.log(`  YouTube privacy: ${privacy}`);if(deployment.privateTest?.passed)console.log(`  Private test: PASS (${deployment.privateTest.videoId||'video id recorded'})`);
  const uploadChunk=deployment.config?.uploadChunk,uploadRetry=deployment.config?.uploadRetry,durable=Boolean(deployment.config?.durableResumableSessions);if(uploadChunk&&uploadRetry)line('YouTube resumable upload',durable,`${Math.round((uploadChunk.bytes||0)/1024)} KiB chunk • retries ${uploadRetry.maxRetries} • timeout ${Math.round((uploadRetry.requestTimeoutMs||0)/1000)}s • jitter ${uploadRetry.jitter?'on':'off'}`);
  const release=await request('/api/admin/release-readiness',true);line('Release candidate gate',Boolean(release.candidateReady),`${release.verdict||'UNKNOWN'} • v${release.release?.version||'?'} • ${String(release.release?.revision||'unknown').slice(0,12)}`);if(Array.isArray(release.blockers)&&release.blockers.length)console.log(`  Release blockers: ${release.blockers.join(' | ')}`);if(Array.isArray(release.warnings)&&release.warnings.length)console.log(`  Release warnings: ${release.warnings.join(' | ')}`);line('LIVE activation readiness',Boolean(release.activationReady),release.liveOperational?'LIVE OPERATIONAL':release.activationReady?'READY TO ENABLE LIVE':'NOT READY');
  const activation=await request('/api/admin/activation-wizard',true),activationState=activation.state||{},kill=activation.killSwitch||{},guard=activation.guard||{};line('Production activation wizard',!kill.engaged,kill.engaged?`KILL SWITCH • ${kill.reason||'engaged'}`:`${activationState.armed?'ARMED':'DISARMED'} • max ${String(activationState.maxPrivacy||'private').toUpperCase()} • env ${String(activation.privacy||'private').toUpperCase()}`);
  const rollout=await request('/api/admin/public-rollout',true),rolloutStatus=String(rollout.state?.publicRolloutStatus||'idle'),controlledPublicLock=activation.privacy==='public'&&Boolean(activationState.publicApprovedAt)&&['idle','canary_queued','watching'].includes(rolloutStatus)&&!rollout.killSwitch?.engaged;line('Production publish guard',Boolean(guard.allowed||controlledPublicLock),guard.allowed?(guard.reason||'ALLOW'):(controlledPublicLock?`CONTROLLED LOCK • rollout ${rolloutStatus.toUpperCase()}`:(guard.reason||'BLOCK')));line('Controlled Public Rollout',rolloutStatus!=='failed',`${rolloutStatus.toUpperCase()} • ${rollout.normalPublicOpen?'normal PUBLIC OPEN':'normal PUBLIC LOCKED'}${rollout.state?.publicWatchEndsAt?` • watch until ${rollout.state.publicWatchEndsAt}`:''}`);
  const ramp=await request('/api/admin/public-ramp',true),rampState=ramp.state||{},rampUsage=ramp.usage||{},rampLimits=ramp.limits||{};line('Gradual Public Ramp',!rampState.circuitOpen,`Stage ${rampState.stage||1} • 60m ${rampUsage.hour||0}/${rampLimits.hourly||0} • day ${rampUsage.day||0}/${rampLimits.daily||0} • min ${rampLimits.minMinutes||0}m${rampState.circuitOpen?` • CIRCUIT OPEN: ${rampState.circuitReason||'review required'}`:''}`);if(ramp.nextAllowedAt)console.log(`  Public next allowed: ${ramp.nextAllowedAt}`);
  const contentSafety=await request('/api/admin/content-safety',true),csCfg=contentSafety.config||{},contentSafetyReady=Number(csCfg.windowHours||0)>0&&Number(csCfg.titleSimilarity||0)>0&&Number(csCfg.bodySimilarity||0)>0;line('Content Safety duplicate guard',contentSafetyReady,`${csCfg.windowHours||'?'}h • title ≥${csCfg.titleSimilarity||'?'} • body ≥${csCfg.bodySimilarity||'?'} • ${contentSafety.recentFingerprints||0} fingerprints`);
  const remoteDetail=activation.remoteCanaryFresh?`${activationState.remoteCanaryVideoId||'?'} • ${activationState.remoteCanaryChannelId||'?'} • ${activationState.remoteCanaryPrivacyStatus||'?'} • ${activationState.remoteCanaryUploadStatus||'?'} / ${activationState.remoteCanaryProcessingStatus||'?'}`:activationState.remoteCanaryVerifiedAt?`STALE/MISMATCH • last ${activationState.remoteCanaryVerifiedAt}`:'not verified';line('Remote Canary promotion evidence',Boolean(activation.remoteCanaryFresh),remoteDetail);
  if(strict){if(overall==='red')throw new Error('Production monitor reports RED');if(!ops.readOnly||!ops.noSideEffects)throw new Error('AI operations assistant safety contract is not read-only');if(!deployment.configurationReady)throw new Error('Publisher configuration is not ready');if(!durable)throw new Error('YouTube durable resumable upload is not enabled');if(!release.candidateReady)throw new Error(`Release candidate is NO-GO: ${(release.blockers||[]).join('; ')}`);if(kill.engaged)throw new Error('Production Kill Switch is engaged');if(rolloutStatus==='failed')throw new Error(`Controlled Public Rollout FAILED: ${rollout.state?.publicRolloutFailureReason||'unknown'}`);if(rampState.circuitOpen)throw new Error(`Public Ramp Circuit OPEN: ${rampState.circuitReason||'operator review required'}`);if(!contentSafetyReady)throw new Error('Content Safety duplicate guard is unavailable');if(process.env.PUBLISH_LIVE_ENABLED==='true'&&activation.privacy!=='private'&&!guard.allowed&&!controlledPublicLock)throw new Error(`LIVE privacy ${activation.privacy} requested but Activation Guard is closed: ${guard.reason||'unknown'}`);if(activationState.maxPrivacy==='public'&&!activationState.publicApprovedAt)throw new Error('PUBLIC ceiling exists without explicit Public approval evidence');if(rollout.normalPublicOpen&&!guard.allowed)throw new Error('Public Rollout says OPEN but Activation Guard is closed')}
  console.log('Production check completed.');
}catch(e){console.error(`Production check failed: ${e instanceof Error?e.message:String(e)}`);process.exit(1)}
