import { Router } from 'express';
import { z } from 'zod';
import { all, run } from '../storage/db.js';
import { accessOf, authStatus, createPersonalApiKey, defaultChannelName, requireAdmin } from './access.js';

export const accountRouter=Router();
accountRouter.get('/public-config',(_q,r)=>r.json({productName:'VietNewsFlow AI',clerkEnabled:authStatus.clerkEnabled,clerkPublishableKey:authStatus.clerkEnabled?process.env.CLERK_PUBLISHABLE_KEY:null}));
accountRouter.get('/account/me',(_q,r)=>{const a=accessOf(r);if(a.accountId==='legacy-admin')return r.json({...a,channelName:defaultChannelName()});const account=all<any>('SELECT id,email,role,plan,status,created_at FROM accounts WHERE id=?',a.accountId)[0];const channel=all<any>('SELECT id,name,tagline,logo_url,primary_color,secondary_color FROM channels WHERE owner_id=? ORDER BY is_default DESC,created_at LIMIT 1',a.accountId)[0];return r.json({account,channel})});
accountRouter.put('/account/channel',(q,r)=>{const a=accessOf(r);if(a.accountId==='legacy-admin')return r.status(409).json({error:'Hãy đăng nhập bằng Clerk để lưu hồ sơ kênh riêng'});const p=z.object({name:z.string().trim().min(2).max(60),tagline:z.string().trim().max(120).optional(),logoUrl:z.string().url().optional().or(z.literal('')),primaryColor:z.string().regex(/^#[0-9a-f]{6}$/i).optional(),secondaryColor:z.string().regex(/^#[0-9a-f]{6}$/i).optional()}).safeParse(q.body||{});if(!p.success)return r.status(400).json({error:'Hồ sơ kênh không hợp lệ',details:p.error.flatten()});const now=new Date().toISOString();run('UPDATE channels SET name=?,tagline=?,logo_url=?,primary_color=COALESCE(?,primary_color),secondary_color=COALESCE(?,secondary_color),updated_at=? WHERE id=(SELECT id FROM channels WHERE owner_id=? ORDER BY is_default DESC,created_at LIMIT 1)',p.data.name,p.data.tagline||null,p.data.logoUrl||null,p.data.primaryColor||null,p.data.secondaryColor||null,now,a.accountId);return r.json({ok:true,channelName:p.data.name})});
accountRouter.get('/admin/members',requireAdmin,(_q,r)=>r.json(all<any>('SELECT id,clerk_user_id,email,role,plan,status,created_at FROM accounts ORDER BY created_at DESC')));
accountRouter.put('/admin/members/:id',(q,r)=>{const a=accessOf(r);if(a.role!=='admin')return r.status(403).json({error:'Admin required'});const p=z.object({role:z.enum(['admin','member']).optional(),plan:z.enum(['free','starter','pro']).optional(),status:z.enum(['active','suspended']).optional()}).safeParse(q.body||{});if(!p.success)return r.status(400).json({error:'Cập nhật thành viên không hợp lệ'});const old=all<any>('SELECT * FROM accounts WHERE id=?',q.params.id)[0];if(!old)return r.status(404).json({error:'Không tìm thấy thành viên'});run('UPDATE accounts SET role=?,plan=?,status=?,updated_at=? WHERE id=?',p.data.role||old.role,p.data.plan||old.plan,p.data.status||old.status,new Date().toISOString(),old.id);return r.json({ok:true})});
accountRouter.get('/admin/api-keys',requireAdmin,(_q,r)=>r.json(all<any>('SELECT k.id,k.owner_id,k.name,k.key_prefix,k.last_used_at,k.revoked_at,k.created_at,a.email,a.plan FROM api_keys k JOIN accounts a ON a.id=k.owner_id ORDER BY k.created_at DESC')));
accountRouter.post('/admin/api-keys',requireAdmin,(q,r)=>{const p=z.object({accountId:z.string().uuid(),name:z.string().trim().min(2).max(80).default('Khóa mặc định')}).safeParse(q.body||{});if(!p.success)return r.status(400).json({error:'Thông tin tạo khóa không hợp lệ'});if(!all<any>('SELECT id FROM accounts WHERE id=?',p.data.accountId)[0])return r.status(404).json({error:'Không tìm thấy thành viên'});return r.status(201).json({...createPersonalApiKey(p.data.accountId,p.data.name),warning:'Hãy sao chép ngay. Khóa bí mật sẽ không hiển thị lại.'})});
accountRouter.delete('/admin/api-keys/:id',requireAdmin,(q,r)=>{run('UPDATE api_keys SET revoked_at=? WHERE id=?',new Date().toISOString(),q.params.id);return r.json({ok:true})});
