import { Router } from 'express';
import { z } from 'zod';
import { all, run } from '../storage/db.js';
import { accessOf, authStatus, createPersonalApiKey, defaultChannelName, requireAdmin } from './access.js';
import { planUsage,PLAN_DEFAULTS,SUPPORT_ZALO } from '../billing/plans.js';

export const accountRouter=Router();
accountRouter.get('/public-config',(_q,r)=>r.json({productName:'VietNewsFlow AI',clerkEnabled:authStatus.clerkEnabled,clerkPublishableKey:authStatus.clerkEnabled?process.env.CLERK_PUBLISHABLE_KEY:null}));
accountRouter.get('/account/me',(_q,r)=>{const a=accessOf(r);if(a.accountId==='legacy-admin')return r.json({...a,channelName:defaultChannelName(),usage:planUsage(a)});const account=all<any>('SELECT id,email,role,plan,status,daily_limit,total_limit,created_at FROM accounts WHERE id=?',a.accountId)[0];const channel=all<any>('SELECT id,name,tagline,logo_url,primary_color,secondary_color FROM channels WHERE owner_id=? ORDER BY is_default DESC,created_at LIMIT 1',a.accountId)[0];return r.json({account,channel,usage:planUsage(a)})});
accountRouter.get('/account/usage',(_q,r)=>r.json({...planUsage(accessOf(r)),plans:PLAN_DEFAULTS,supportZalo:SUPPORT_ZALO}));
accountRouter.put('/account/channel',(q,r)=>{const a=accessOf(r);if(a.accountId==='legacy-admin')return r.status(409).json({error:'Hãy đăng nhập bằng Clerk để lưu hồ sơ kênh riêng'});const p=z.object({name:z.string().trim().min(2).max(60),tagline:z.string().trim().max(120).optional(),logoUrl:z.string().url().optional().or(z.literal('')),primaryColor:z.string().regex(/^#[0-9a-f]{6}$/i).optional(),secondaryColor:z.string().regex(/^#[0-9a-f]{6}$/i).optional()}).safeParse(q.body||{});if(!p.success)return r.status(400).json({error:'Hồ sơ kênh không hợp lệ',details:p.error.flatten()});const now=new Date().toISOString();run('UPDATE channels SET name=?,tagline=?,logo_url=?,primary_color=COALESCE(?,primary_color),secondary_color=COALESCE(?,secondary_color),updated_at=? WHERE id=(SELECT id FROM channels WHERE owner_id=? ORDER BY is_default DESC,created_at LIMIT 1)',p.data.name,p.data.tagline||null,p.data.logoUrl||null,p.data.primaryColor||null,p.data.secondaryColor||null,now,a.accountId);return r.json({ok:true,channelName:p.data.name})});
accountRouter.get('/admin/members',requireAdmin,(_q,r)=>r.json(all<any>(`SELECT a.id,a.clerk_user_id,a.email,a.role,a.plan,a.status,a.daily_limit,a.total_limit,a.created_at,
 (SELECT name FROM channels WHERE owner_id=a.id ORDER BY is_default DESC,created_at LIMIT 1) channel_name,
 (SELECT COUNT(*) FROM api_keys WHERE owner_id=a.id AND revoked_at IS NULL) active_api_keys,
 (SELECT COUNT(*) FROM render_jobs WHERE owner_id=a.id AND status!='failed') videos_total,
 (SELECT COUNT(*) FROM render_jobs WHERE owner_id=a.id AND status!='failed' AND created_at>=datetime('now','+7 hours','start of day','-7 hours')) videos_today
 FROM accounts a ORDER BY a.created_at DESC`)));
accountRouter.put('/admin/members/:id',requireAdmin,(q,r)=>{const a=accessOf(r);const p=z.object({role:z.enum(['admin','member']).optional(),plan:z.enum(['free','starter','pro']).optional(),status:z.enum(['active','suspended']).optional(),dailyLimit:z.number().int().min(1).max(500).nullable().optional(),totalLimit:z.number().int().min(1).max(10000).nullable().optional()}).safeParse(q.body||{});if(!p.success)return r.status(400).json({error:'Cập nhật thành viên không hợp lệ'});const old=all<any>('SELECT * FROM accounts WHERE id=?',q.params.id)[0];if(!old)return r.status(404).json({error:'Không tìm thấy thành viên'});if(old.id===a.accountId&&p.data.status==='suspended')return r.status(409).json({error:'Không thể tự khóa tài khoản quản trị đang đăng nhập'});if(old.id===a.accountId&&p.data.role==='member')return r.status(409).json({error:'Không thể tự hạ quyền tài khoản quản trị đang đăng nhập'});run('UPDATE accounts SET role=?,plan=?,status=?,daily_limit=?,total_limit=?,updated_at=? WHERE id=?',p.data.role||old.role,p.data.plan||old.plan,p.data.status||old.status,p.data.dailyLimit===undefined?old.daily_limit:p.data.dailyLimit,p.data.totalLimit===undefined?old.total_limit:p.data.totalLimit,new Date().toISOString(),old.id);return r.json({ok:true})});
accountRouter.get('/admin/api-keys',requireAdmin,(_q,r)=>r.json(all<any>('SELECT k.id,k.owner_id,k.name,k.key_prefix,k.last_used_at,k.revoked_at,k.created_at,a.email,a.plan FROM api_keys k JOIN accounts a ON a.id=k.owner_id ORDER BY k.created_at DESC')));
accountRouter.post('/admin/api-keys',requireAdmin,(q,r)=>{const p=z.object({accountId:z.string().uuid(),name:z.string().trim().min(2).max(80).default('Khóa mặc định')}).safeParse(q.body||{});if(!p.success)return r.status(400).json({error:'Thông tin tạo khóa không hợp lệ'});if(!all<any>('SELECT id FROM accounts WHERE id=?',p.data.accountId)[0])return r.status(404).json({error:'Không tìm thấy thành viên'});return r.status(201).json({...createPersonalApiKey(p.data.accountId,p.data.name),warning:'Hãy sao chép ngay. Khóa bí mật sẽ không hiển thị lại.'})});
accountRouter.delete('/admin/api-keys/:id',requireAdmin,(q,r)=>{const key=all<any>('SELECT id,revoked_at FROM api_keys WHERE id=?',q.params.id)[0];if(!key)return r.status(404).json({error:'Không tìm thấy API key'});if(!key.revoked_at)run('UPDATE api_keys SET revoked_at=? WHERE id=?',new Date().toISOString(),q.params.id);return r.json({ok:true})});
