import { all,run } from '../storage/db.js';
import { productionActivationState } from './activation-state.js';

export type PublicRampStage=1|2|3;
export interface PublicRampState{ownerId:string;stage:PublicRampStage;circuitOpen:boolean;circuitReason?:string;circuitOpenedAt?:string;cooldownUntil?:string;promotedAt?:string;promotedBy?:string;resetAt?:string;resetBy?:string;failureEvents?:string[];updatedAt?:string}
type StateRow={value_json:string;updated_at:string};
type JobRow={id:string;status:string;published_at?:string;scheduled_at?:string;created_at:string;error?:string;public_canary?:number;publish_privacy?:string};
const key=(ownerId:string)=>`publish.public-ramp:${ownerId}`;
function num(name:string,fallback:number,min=1,max=1000){const n=Number(process.env[name]||fallback);return Math.max(min,Math.min(max,Number.isFinite(n)?n:fallback))}
export function stageLimits(stage:PublicRampStage){
  const base=stage===1?{hourly:1,daily:3,minMinutes:60}:stage===2?{hourly:2,daily:6,minMinutes:30}:{hourly:3,daily:12,minMinutes:20};
  return{hourly:num(`PUBLIC_RAMP_STAGE${stage}_HOURLY`,base.hourly,1,24),daily:num(`PUBLIC_RAMP_STAGE${stage}_DAILY`,base.daily,1,200),minMinutes:num(`PUBLIC_RAMP_STAGE${stage}_MIN_INTERVAL_MINUTES`,base.minMinutes,1,1440)};
}
function readState(ownerId:string):PublicRampState{const row=all<StateRow>('SELECT value_json,updated_at FROM system_runtime_state WHERE state_key=? LIMIT 1',key(ownerId))[0];let value:any={ownerId,stage:1,circuitOpen:false,failureEvents:[]};try{if(row)value={...value,...JSON.parse(row.value_json)}}catch{}return row?{...value,updatedAt:row.updated_at}:value}
function writeState(ownerId:string,next:PublicRampState){const now=new Date().toISOString();run('INSERT INTO system_runtime_state(state_key,value_json,updated_at) VALUES(?,?,?) ON CONFLICT(state_key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at',key(ownerId),JSON.stringify(next),now);return{...next,updatedAt:now}}
export function publicRampState(ownerId:string){return readState(ownerId)}
function publicJobs(ownerId:string,excludeJobId?:string){return all<JobRow>("SELECT id,status,published_at,scheduled_at,created_at,error,public_canary,publish_privacy FROM publish_jobs WHERE owner_id=? AND platform='youtube' AND dry_run=0 AND deployment_test=0 AND status NOT IN ('failed','cancelled') AND (publish_privacy='public' OR public_canary=1) ORDER BY created_at DESC",ownerId).filter(x=>x.id!==excludeJobId)}
function when(row:JobRow){const raw=row.status==='published'&&row.published_at?row.published_at:(row.scheduled_at||row.created_at);const t=Date.parse(raw);return Number.isFinite(t)?t:0}
function vnDayBounds(target:number){const shifted=target+7*3600000,d=new Date(shifted),startShifted=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()),start=startShifted-7*3600000;return{start,end:start+86400000}}
export class PublicRampGuardError extends Error{kind:'rate'|'circuit';nextAllowedAt?:string;constructor(message:string,kind:'rate'|'circuit',nextAllowedAt?:string){super(message);this.name='PublicRampGuardError';this.kind=kind;this.nextAllowedAt=nextAllowedAt}}
export function publicRampSnapshot(ownerId:string,input:{targetAt?:string;excludeJobId?:string}={}){
  const state=readState(ownerId),limits=stageLimits(state.stage),targetRaw=input.targetAt?Date.parse(input.targetAt):Date.now(),target=Number.isFinite(targetRaw)?targetRaw:Date.now(),jobs=publicJobs(ownerId,input.excludeJobId),times=jobs.map(when).filter(Boolean),hourTimes=times.filter(t=>Math.abs(t-target)<3600000),day=vnDayBounds(target),dayTimes=times.filter(t=>t>=day.start&&t<day.end),nearest=times.length?times.reduce((a,b)=>Math.abs(b-target)<Math.abs(a-target)?b:a):0,minMs=limits.minMinutes*60000;
  const reasons:string[]=[];let nextAllowed=target;
  if(state.circuitOpen){reasons.push(`Circuit OPEN: ${state.circuitReason||'operator review required'}`);const c=Date.parse(String(state.cooldownUntil||''));if(Number.isFinite(c))nextAllowed=Math.max(nextAllowed,c)}
  if(hourTimes.length>=limits.hourly){reasons.push(`Đã đạt ${limits.hourly} PUBLIC trong cửa sổ 60 phút`);nextAllowed=Math.max(nextAllowed,Math.min(...hourTimes)+3600000)}
  if(dayTimes.length>=limits.daily){reasons.push(`Đã đạt ${limits.daily} PUBLIC trong ngày Việt Nam`);nextAllowed=Math.max(nextAllowed,day.end)}
  if(nearest&&Math.abs(nearest-target)<minMs){reasons.push(`Khoảng cách tối thiểu ${limits.minMinutes} phút chưa đạt`);nextAllowed=Math.max(nextAllowed,nearest+minMs)}
  const activation=productionActivationState(ownerId),rolloutReady=activation.publicRolloutStatus==='completed'&&Boolean(activation.publicRolloutCompletedAt);
  if(!rolloutReady)reasons.push('Controlled Public Rollout chưa COMPLETED');
  return{state,limits,rolloutReady,targetAt:new Date(target).toISOString(),usage:{hour:hourTimes.length,day:dayTimes.length,totalPublic:times.length},allowed:reasons.length===0,reasons,nextAllowedAt:reasons.length?new Date(nextAllowed).toISOString():undefined,checkedAt:new Date().toISOString()};
}
export function assertPublicRampAllowed(ownerId:string,input:{targetAt?:string;excludeJobId?:string}={}){const x=publicRampSnapshot(ownerId,input);if(x.allowed)return x;if(x.state.circuitOpen)throw new PublicRampGuardError(`Public Ramp Circuit OPEN: ${x.reasons.join(' | ')}`,'circuit',x.nextAllowedAt);throw new PublicRampGuardError(`Public Ramp giới hạn publish: ${x.reasons.join(' | ')}`,'rate',x.nextAllowedAt)}
export function openPublicRampCircuit(ownerId:string,reason:string,actor='system:public-ramp'){const now=Date.now(),cooldown=num('PUBLIC_RAMP_CIRCUIT_COOLDOWN_MINUTES',60,5,1440)*60000,state=readState(ownerId);return writeState(ownerId,{...state,ownerId,circuitOpen:true,circuitReason:String(reason).slice(0,500),circuitOpenedAt:new Date(now).toISOString(),cooldownUntil:new Date(now+cooldown).toISOString()})}
function isHardLimit(message:string){return /(429|quotaExceeded|uploadRateLimitExceeded|uploadLimitExceeded|rateLimitExceeded|daily video upload limit|quota)/i.test(message)}
function isTransient(message:string){return /(500|502|503|504|ECONN|ETIMEDOUT|network|fetch failed|socket hang up)/i.test(message)}
export function recordPublicRampFailure(ownerId:string,message:string,opts:{needsReconcile?:boolean}={}){const now=Date.now(),windowMs=num('PUBLIC_RAMP_CIRCUIT_WINDOW_MINUTES',30,5,240)*60000,threshold=num('PUBLIC_RAMP_CIRCUIT_FAILURES',2,1,20),state=readState(ownerId),events=(state.failureEvents||[]).map(Date.parse).filter(t=>Number.isFinite(t)&&now-t<=windowMs);events.push(now);const next=writeState(ownerId,{...state,ownerId,failureEvents:events.slice(-20).map(t=>new Date(t).toISOString())});if(opts.needsReconcile)return openPublicRampCircuit(ownerId,'needs_reconcile xuất hiện trong PUBLIC publish');if(isHardLimit(message))return openPublicRampCircuit(ownerId,`YouTube rate/quota guard: ${message}`);if(isTransient(message)&&events.length>=threshold)return openPublicRampCircuit(ownerId,`${events.length} lỗi mạng/5xx trong ${Math.round(windowMs/60000)} phút: ${message}`);return next}
export function recordPublicRampSuccess(ownerId:string){const state=readState(ownerId);if(state.circuitOpen)return state;return writeState(ownerId,{...state,ownerId,failureEvents:[]})}
export function promotePublicRamp(ownerId:string,actor:string){const state=readState(ownerId);if(state.circuitOpen)throw new Error('Không thể Promote khi Public Ramp Circuit đang OPEN');if(state.stage>=3)throw new Error('Public Ramp đã ở Stage 3');const stage=(state.stage+1) as PublicRampStage;return writeState(ownerId,{...state,ownerId,stage,promotedAt:new Date().toISOString(),promotedBy:actor,failureEvents:[]})}
export function resetPublicRampCircuit(ownerId:string,actor:string){const state=readState(ownerId);if(!state.circuitOpen)return state;const until=Date.parse(String(state.cooldownUntil||''));if(Number.isFinite(until)&&Date.now()<until)throw new Error(`Circuit cooldown chưa hết (${state.cooldownUntil})`);return writeState(ownerId,{...state,ownerId,circuitOpen:false,circuitReason:undefined,circuitOpenedAt:undefined,cooldownUntil:undefined,resetAt:new Date().toISOString(),resetBy:actor,failureEvents:[]})}
