import { Router } from 'express';
import { all } from '../storage/db.js';
import { accessOf,requireAdmin } from '../auth/access.js';
import { auditActor,recordAuditEvent } from '../system/audit.js';
import { releaseCandidateSnapshot } from '../system/release-readiness.js';
import { productionActivationState } from './activation-state.js';
import { promotePublicRamp,publicRampSnapshot,resetPublicRampCircuit } from './public-ramp.js';

export const publicRampRouter=Router();
function owner(res:any){return accessOf(res).accountId}
function actor(res:any){return auditActor(accessOf(res))}
function audit(res:any,action:string,summary:string,metadata?:unknown){const a=actor(res);recordAuditEvent({ownerId:owner(res),actor:a,action,targetType:'public-ramp',targetId:owner(res),summary,metadata})}
function num(name:string,fallback:number,min=1,max=10000){const n=Number(process.env[name]||fallback);return Math.max(min,Math.min(max,Number.isFinite(n)?n:fallback))}
function stageEvidence(ownerId:string){const state=publicRampSnapshot(ownerId).state,activation=productionActivationState(ownerId),since=state.promotedAt||activation.publicRolloutCompletedAt||new Date(0).toISOString(),rows=all<{published_at:string}>("SELECT published_at FROM publish_jobs WHERE owner_id=? AND platform='youtube' AND dry_run=0 AND deployment_test=0 AND public_canary=0 AND publish_privacy='public' AND status='published' AND published_at>=? ORDER BY published_at",ownerId,since),stableHours=num('PUBLIC_RAMP_PROMOTE_STABLE_HOURS',24,1,720),minSuccess=num('PUBLIC_RAMP_PROMOTE_MIN_SUCCESSES',3,1,100),sinceMs=Date.parse(since),stable=Number.isFinite(sinceMs)&&Date.now()-sinceMs>=stableHours*3600000;return{since,successes:rows.length,stableHours,minSuccess,stable}}
async function snapshot(ownerId:string){const ramp=publicRampSnapshot(ownerId),release=await releaseCandidateSnapshot(ownerId),evidence=stageEvidence(ownerId),healthy=Boolean(release.candidateReady&&release.monitor.overall!=='red'&&release.queues.needsReconcile===0&&release.queues.uncertainSessions===0),canPromote=healthy&&!ramp.state.circuitOpen&&ramp.state.stage<3&&ramp.rolloutReady&&evidence.stable&&evidence.successes>=evidence.minSuccess;return{...ramp,release:{verdict:release.verdict,monitor:release.monitor.overall,queues:release.queues},evidence,healthy,canPromote,canResetCircuit:Boolean(ramp.state.circuitOpen&&healthy&&(!ramp.state.cooldownUntil||Date.now()>=Date.parse(ramp.state.cooldownUntil))),checkedAt:new Date().toISOString()}}
publicRampRouter.use('/admin/public-ramp',requireAdmin);
publicRampRouter.get('/admin/public-ramp',async(_req,res)=>{try{return res.json(await snapshot(owner(res)))}catch(e){return res.status(500).json({error:e instanceof Error?e.message:String(e)})}});
publicRampRouter.post('/admin/public-ramp/promote',async(req,res)=>{if(String(req.body?.confirmation||'')!=='PROMOTE PUBLIC RAMP')return res.status(400).json({error:'Cần nhập chính xác: PROMOTE PUBLIC RAMP'});try{const ownerId=owner(res),before=await snapshot(ownerId);if(!before.canPromote)return res.status(409).json({error:'Chưa đủ điều kiện Promote: cần Release GO, Monitor không RED, Reconcile clear, circuit CLOSED, đủ thời gian ổn định và số publish thành công',snapshot:before});const next=promotePublicRamp(ownerId,actor(res).id);audit(res,'public-ramp.promote',`Promote Public Ramp Stage ${before.state.stage} → ${next.stage}`,{from:before.state.stage,to:next.stage,evidence:before.evidence});return res.json(await snapshot(ownerId))}catch(e){return res.status(409).json({error:e instanceof Error?e.message:String(e)})}});
publicRampRouter.post('/admin/public-ramp/reset-circuit',async(req,res)=>{if(String(req.body?.confirmation||'')!=='RESET PUBLIC CIRCUIT')return res.status(400).json({error:'Cần nhập chính xác: RESET PUBLIC CIRCUIT'});try{const ownerId=owner(res),before=await snapshot(ownerId);if(!before.canResetCircuit)return res.status(409).json({error:'Chưa thể reset circuit: cooldown chưa hết hoặc production health chưa sạch',snapshot:before});const next=resetPublicRampCircuit(ownerId,actor(res).id);audit(res,'public-ramp.circuit-reset','Reset Public Ramp Circuit sau cooldown và health checks',{previousReason:before.state.circuitReason,stage:next.stage});return res.json(await snapshot(ownerId))}catch(e){return res.status(409).json({error:e instanceof Error?e.message:String(e)})}});
